const family = (model, file, sourceUrl, sourcePageUrl) => ({
  model,
  file,
  sourceUrl,
  sourcePageUrl,
  matchScope: 'ILLUSTRATIVE',
  matchNote: `Official current Ford Brasil ${model} family image shared by the manufacturer across the listed configurations; it does not establish color or trim-specific appearance.`,
});

const exact = (model, name, file, sourceUrl, sourcePageUrl) => ({
  model,
  name,
  file,
  sourceUrl,
  sourcePageUrl,
  matchScope: 'EXACT_CONFIGURATION',
  matchNote: `Official current Ford Brasil image linked to the ${model} ${name} configuration by the manufacturer page.`,
});

export default [
  exact(
    'Ranger',
    'XL 2.0 CH Diesel 4x4 MT',
    'ranger-xl-ch-mt.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/nova-geracao-ranger/models/xl-20-ch-diesel-4x4-mt/fbr-ranger-xl-ch-4x4-mt.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'XL 2.0 CH Diesel 4x4 AT',
    'ranger-xl-ch-at.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/nova-geracao-ranger/models/xl-20-ch-diesel-4x4-at/fbr-ranger-xl-ch-4x4-at.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'XL 2.0 CS Diesel 4x4 MT',
    'ranger-xl-cs-mt.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/nova-geracao-ranger/models/xl-20-cs-diesel-4x4-mt/fbr-ranger-xl-cs-4x4-mt.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'XL 2.0 CS Diesel 4x4 AT',
    'ranger-xl-cs-at.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/nova-geracao-ranger/models/xl-20-cs-diesel-4x4-at/fbr-ranger-xl-cs-4x4-at.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'XL 2.0 CD Diesel 4x4 MT',
    'ranger-xl-cd-mt.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/nova-geracao-ranger/models/xl-20-cd-diesel-4x4-mt/fbr-ranger-xl-cd-4x4-mt.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'XL 2.0 CD Diesel 4x4 AT',
    'ranger-xl-cd-at.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/nova-geracao-ranger/models/xl-20-cd-diesel-4x4-at/fbr-ranger-xl-cd-4x4-at.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'XLS 2.0 Diesel 4x4 AT',
    'ranger-xls-20.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/nova-ranger/models/xls_2_0_diesel_4x4_at/fbr-ford-pro-transit-xls-4x4.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'Black 2.0L 4x2 AT Diesel',
    'ranger-black.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/nova-geracao-ranger/models/black-2-0-diesel-4x2-at/showroom/fbr-vehicle-group-ranger-black.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'XLS 3.0 V6 Diesel 4WD AT',
    'ranger-xls-v6.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/nova-ranger/models/xls-3-0-diesel-4wd-at/fbr-ranger-xl-2-o-diesel-4x4-mt.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'XLT 3.0 V6 Diesel 4WD AT',
    'ranger-xlt-v6.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/nova-ranger/models/xlt-3-0-v6-diesel-4wd-at-2024/fbr-nova-ranger-versoe-xlt.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'Limited 3.0 V6 Diesel 4WD AT',
    'ranger-limited-v6.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/nova-ranger/models/limited-3-0-v6-diesel-4wd-at-2024/fbr-ranger-limited-v6-diesel-4wd-at.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  exact(
    'Ranger',
    'Limited 3.0 V6 Diesel 4WD AT + Kit Opcional',
    'ranger-limited-kit.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/nova-ranger/models/limited-pacote-opcional-3-0-v6-diesel-4wd-at-2024/fbr-ranger-limited-v6-diesel-4wd-at.jpg',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
  ),
  family(
    'Ranger Raptor',
    'ranger-raptor.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/ranger-raptor/overview/billboard-carousel/fbr-billboard-carousel-ranger-raptor.jpg',
    'https://www.ford.com.br/picapes/ranger-raptor/raptor-4wd-at/',
  ),
  exact(
    'Maverick',
    'Black',
    'maverick-black.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/maverick/overview/billboards/fbr-billboard-maverick-black.jpg',
    'https://www.ford.com.br/picapes/maverick/versoes/compare/',
  ),
  exact(
    'Maverick',
    'Tremor',
    'maverick-tremor.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/maverick-tremor/overview/billboards/fbr-maverick-tremor-billboard-principal.jpg',
    'https://www.ford.com.br/picapes/maverick/versoes/compare/',
  ),
  exact(
    'Maverick',
    'Hybrid',
    'maverick-hybrid.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/maverick-hybrid/overview/billboard/fbr-maverick-hybrid-billboard.jpg',
    'https://www.ford.com.br/picapes/maverick/versoes/compare/',
  ),
  exact(
    'F-150',
    'Lariat',
    'f150-lariat.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/f-150/models/lariat-chrome/fbr-tremor-vesoes-cromada.jpg',
    'https://www.ford.com.br/picapes/f-150/compare-as-versoes/',
  ),
  exact(
    'F-150',
    'Lariat Black',
    'f150-lariat-black.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/f-150/models/lariat-black/fbr-tremor-vesoes-black.jpg',
    'https://www.ford.com.br/picapes/f-150/compare-as-versoes/',
  ),
  exact(
    'F-150',
    'Tremor',
    'f150-tremor.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/f-150/models/tremor/fbr-versiones-f150-tremor.jpg',
    'https://www.ford.com.br/picapes/f-150/compare-as-versoes/',
  ),
  family(
    'Territory',
    'territory.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/territory/overview/billboards/fbr-billboard-novo-territory.jpg',
    'https://www.ford.com.br/suvs-e-crossovers/territory/titanium/',
  ),
  family(
    'Bronco Sport',
    'bronco-sport.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/bronco-sport/overview/billboard/fbr-ford-nameplate-billboard-bronco-sport.jpg',
    'https://www.ford.com.br/suvs-e-crossovers/bronco-sport/badlands/',
  ),
  family(
    'Mustang Mach-E',
    'mustang-mach-e.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/mustang-mach-e/overview/billboard/fbr-mustang-mach-billboard.jpg',
    'https://www.ford.com.br/performance/mustang-mach-e/gt-performance/',
  ),
  family(
    'Mustang Dark Horse',
    'mustang-dark-horse.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/mustang-dark-horse/overview/billboard/fbr-mustang-dark-horse-billboard.jpg',
    'https://www.ford.com.br/performance/mustang-dark-horse/dark-horse/',
  ),
  family(
    'Transit Minibus',
    'transit-minibus.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/transit-minibus/overview/billboard/fbr-transit-minibus-overview-billboard.jpg',
    'https://www.ford.com.br/veiculos-comerciais/transit-minibus/compare-as-versoes/',
  ),
  family(
    'Transit Furgão',
    'transit-furgao.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/transit-furgao/overview/billboard/fbr-transit-furgao-overview-billboard.jpg',
    'https://www.ford.com.br/veiculos-comerciais/transit-furgao/compare-as-versoes/',
  ),
  family(
    'E-Transit Furgão',
    'e-transit-furgao.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/transit-furgao/overview/billboard/fbr-e-transit-furgao-overview-billboard.jpg',
    'https://www.ford.com.br/veiculos-comerciais/e-transit-furgao/compare-as-versoes/',
  ),
  family(
    'Transit Chassi',
    'transit-chassi.jpg',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/transit-chassi/overview/billboard/fbr-transit-chassi-overview-billboard.jpg',
    'https://www.ford.com.br/veiculos-comerciais/transit-chassi/compare-as-versoes/',
  ),
];
