const capturedOn = '2026-09-12';

const source = (key, title, url, sha256, publishedOn = null) => ({
  key,
  title,
  path: new URL(url).pathname,
  sha256,
  provenance: 'PRIMARY_SOURCE',
  upstreamUrls: [url],
  capturedOn,
  publishedOn,
});

const sources = [
  source(
    'ford_current_lineup',
    'Escolha o modelo do seu próximo veículo Ford',
    'https://www.ford.com.br/todos-os-veiculos/',
    'c0849496f9c73167809863afc75329947314c14bdb8a2ead65137b8970ccbaff',
  ),
  source(
    'ranger_compare',
    'Nova Geração Ranger — Compare as versões',
    'https://www.ford.com.br/picapes/ranger/compare-as-versoes/',
    '47c2373624d7076dd8c238afd2f3657465bd94fb0a6548b20f9a73ed95323159',
  ),
  source(
    'ranger_xl_pdf',
    'Nova Geração Ford Ranger — Ficha técnica XL',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/nova-geracao-ranger/update-images/pdf/fbr-nova-ford-ranger-ficha-tecnica.pdf',
    'f02513bb927f0cd6633aa05175aea45bf785d6360acc761b51aa834924cd1c0d',
  ),
  source(
    'ranger_raptor_page',
    'Ranger Raptor 4WD AT',
    'https://www.ford.com.br/picapes/ranger-raptor/raptor-4wd-at/',
    'd98ed4259878d30d051bf651d10359826598fca565af87b9157bf2393b0e2878',
  ),
  source(
    'ranger_raptor_pdf',
    'Ranger Raptor — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/ranger-raptor/pdf/fbr-ranger-raptor-ficha-tecnica.pdf',
    'dc83c3671974587fcf80dd3f3cabfbf1dd724053b3f4e6eb31f4f54afc1080cf',
  ),
  source(
    'maverick_compare',
    'Ford Maverick — Compare as versões',
    'https://www.ford.com.br/picapes/maverick/versoes/compare/',
    'f1bb4a94de34e3e8245f7fe29a6f35ee8f43a0d0969fc39d909b476398a0a8ba',
  ),
  source(
    'maverick_pdf',
    'Ford Maverick — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/maverick/pdf/v2/v3/fbr-maverick-ficha-tecnica.pdf',
    '2f6ded0eb725912c88831afec674c4c92096983acd2efadc696f26afa20df8a7',
  ),
  source(
    'f150_compare',
    'Ford F-150 — Compare as versões',
    'https://www.ford.com.br/picapes/f-150/compare-as-versoes/',
    'f0f5c7aff5b3e18f9a5215afedebd98d0ab7d9fd81660508eeca9833816a7200',
  ),
  source(
    'f150_pdf',
    'Ford F-150 — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/f-150/overview/pdf/fbr-f-150-ficha-tecnica.pdf',
    '2c888070f2b5ac3561d21dacfddd110a4bfeb56deeb887f349dade30d58d11da',
  ),
  source(
    'territory_page',
    'Ford Territory Titanium',
    'https://www.ford.com.br/suvs-e-crossovers/territory/titanium/',
    '32f0b197743749397518503c3d85c2e9daad656ec36f945150afa1af1f50759e',
  ),
  source(
    'territory_pdf',
    'Ford Territory — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/territory/pdf/fbr-territory-ficha-tecnica.pdf',
    'b959a2f59912f9a6de3b3bc85bc8bb5cefa57eb03e8c99bf795ece0052d5eb90',
  ),
  source(
    'bronco_sport_page',
    'Ford Bronco Sport Badlands',
    'https://www.ford.com.br/suvs-e-crossovers/bronco-sport/badlands/',
    '9441f4860d6b32ae9e63abde645188a60b62a54ad17e7eebd4aa1d5db01a65b8',
  ),
  source(
    'bronco_sport_pdf',
    'Ford Bronco Sport 26.5MY — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/bronco_sport/pdf/fbr-ficha-tecnica-bronco-sport.pdf',
    '139d1dd3aed32d88b47d6dce17e16751f0085090f093334196e1a89605289ed6',
  ),
  source(
    'mustang_mach_e_page',
    'Mustang Mach-E GT Performance',
    'https://www.ford.com.br/performance/mustang-mach-e/gt-performance/',
    'b96f937d4ef52e62903704ecafb9e4f62726e62c10d5df4d08f953d09280a1af',
  ),
  source(
    'mustang_mach_e_pdf',
    'Mustang Mach-E — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/mustang-mach-e/pdf/fbr-ficha-tecnica-mach-e-2025.pdf',
    'cf208ff58616c876c73941151de18a0d8593c537e5dd1ba948921968bd3da0ed',
  ),
  source(
    'mustang_dark_horse_page',
    'Ford Mustang Dark Horse',
    'https://www.ford.com.br/performance/mustang-dark-horse/dark-horse/',
    '015b506e3bb99cf6e682a9b502ed681f59d974c5c0732fdf1e9729b9a9e84984',
  ),
  source(
    'mustang_dark_horse_pdf',
    'Ford Mustang Dark Horse — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2025/mustang-dark-horse/pdf/fbr-ficha-tecnica-mustang-dark-horse.pdf',
    '39f8497c50cd4dfa30880574a5c3932462613c033b1a2520d0dc0745d6926b93',
  ),
  source(
    'transit_minibus_compare',
    'Transit Minibus — Compare as versões',
    'https://www.ford.com.br/veiculos-comerciais/transit-minibus/compare-as-versoes/',
    'ce6c864e50a8043006c335b575d5dae4745e9c711f20c2eb22a5bfed09ba8056',
  ),
  source(
    'transit_minibus_pdf',
    'Ford Transit Minibus — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/transit-minibus/pdf/fbr-transit-minibus-ficha-tecnica.pdf',
    '5e1d1803fe7d4427f444c0ab549dcaa2cd05499aa713453d05010d0073fd743e',
  ),
  source(
    'transit_furgao_compare',
    'Transit Furgão — Compare as versões',
    'https://www.ford.com.br/veiculos-comerciais/transit-furgao/compare-as-versoes/',
    'a5e0f0c5ea182a1bb4f8aee7e8c46bcfc76d1ac9df01fc772eddfddb47067b78',
  ),
  source(
    'transit_furgao_pdf',
    'Ford Transit Furgão — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/transit-furgao/pdf/fbr-transit-furgao-ficha-tecnica.pdf',
    '22d0d17056c0a2dd70f6f036f91bcc31680f2d490fde7ec0d456e59c56479254',
  ),
  source(
    'e_transit_compare',
    'E-Transit Furgão — Compare as versões',
    'https://www.ford.com.br/veiculos-comerciais/e-transit-furgao/compare-as-versoes/',
    'e584cf2acde2c53415add713531ce693aa57310ef13d6397d47b1689f3c52e46',
  ),
  source(
    'e_transit_pdf',
    'Ford E-Transit Furgão — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/e-transit-furgao/pdf/fbr-e-transit_furgao-ft.pdf',
    'dcb53754dcd651b60e172dd5ad25e75f37c2f6c8b9703a2c786d920434971cdb',
  ),
  source(
    'transit_chassi_compare',
    'Transit Chassi — Compare as versões',
    'https://www.ford.com.br/veiculos-comerciais/transit-chassi/compare-as-versoes/',
    '7de85b9e2f24840f04d2e00a07520ed89bf57340587d826ce5c1a6ff7ba2d9da',
  ),
  source(
    'transit_chassi_pdf',
    'Ford Transit Chassi — Ficha técnica',
    'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2026/transit-chassi/pdf/fbr-transit-chassis-ficha-tecnica.pdf',
    'c3d641738f352db7a75fa4f26fe1fac95c107da4ef59113cccfd341a505aa2ea',
  ),
];

const attribute = (code, label, description, valueType, unit = null) => ({
  code,
  label,
  description,
  valueType,
  unit,
});

const attributes = [
  attribute(
    'engine',
    'Motor',
    'Manufacturer-reported engine or motor description.',
    'TEXT',
  ),
  attribute(
    'power_max',
    'Potência máxima',
    'Maximum manufacturer-reported power.',
    'NUMBER',
    'cv',
  ),
  attribute(
    'torque_max',
    'Torque máximo',
    'Maximum manufacturer-reported torque.',
    'NUMBER',
    'Nm',
  ),
  attribute(
    'fuel_type',
    'Combustível',
    'Energy carriers explicitly reported by the source.',
    'LIST',
  ),
  attribute(
    'transmission',
    'Transmissão',
    'Manufacturer-reported transmission.',
    'TEXT',
  ),
  attribute(
    'drivetrain',
    'Tração',
    'Manufacturer-reported driven-wheel system.',
    'TEXT',
  ),
  attribute(
    'driving_modes',
    'Modos de condução',
    'Selectable driving modes reported by the manufacturer.',
    'LIST',
  ),
  attribute(
    'displacement',
    'Cilindrada',
    'Engine displacement.',
    'NUMBER',
    'cm3',
  ),
  attribute('length', 'Comprimento', 'Overall vehicle length.', 'NUMBER', 'mm'),
  attribute(
    'height',
    'Altura',
    'Maximum or manufacturer-reported vehicle height.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'width_with_mirrors',
    'Largura com espelhos',
    'Overall width including mirrors.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'width_without_mirrors',
    'Largura sem espelhos',
    'Overall width excluding mirrors.',
    'NUMBER',
    'mm',
  ),
  attribute('wheelbase', 'Entre eixos', 'Wheelbase.', 'NUMBER', 'mm'),
  attribute(
    'curb_weight',
    'Peso em ordem de marcha',
    'Vehicle mass in running order.',
    'NUMBER',
    'kg',
  ),
  attribute(
    'payload',
    'Capacidade de carga',
    'Maximum payload mass.',
    'NUMBER',
    'kg',
  ),
  attribute(
    'towing_capacity',
    'Capacidade de reboque',
    'Maximum braked towing mass unless qualified otherwise.',
    'NUMBER',
    'kg',
  ),
  attribute(
    'towing_capacity_unbraked',
    'Capacidade de reboque sem freio',
    'Maximum unbraked towing mass.',
    'NUMBER',
    'kg',
  ),
  attribute(
    'fuel_tank',
    'Tanque de combustível',
    'Fuel-tank volume.',
    'NUMBER',
    'L',
  ),
  attribute(
    'adblue_tank',
    'Tanque de Arla 32',
    'Diesel exhaust-fluid tank volume.',
    'NUMBER',
    'L',
  ),
  attribute(
    'passenger_capacity',
    'Número de passageiros',
    'Total occupants, including the driver unless qualified otherwise.',
    'NUMBER',
  ),
  attribute(
    'cargo_bed_volume',
    'Capacidade da caçamba',
    'Open cargo-bed volume.',
    'NUMBER',
    'L',
  ),
  attribute(
    'cargo_volume',
    'Volume máximo de carga',
    'Maximum enclosed cargo volume.',
    'NUMBER',
    'm3',
  ),
  attribute(
    'cargo_volume_vda',
    'Volume de carga VDA',
    'Enclosed cargo volume under the VDA method.',
    'NUMBER',
    'm3',
  ),
  attribute(
    'luggage_volume',
    'Volume do porta-malas',
    'Luggage-compartment volume with seats in use.',
    'NUMBER',
    'L',
  ),
  attribute(
    'luggage_volume_seats_folded',
    'Volume do porta-malas com bancos rebatidos',
    'Luggage volume with rear seats folded.',
    'NUMBER',
    'L',
  ),
  attribute(
    'gross_vehicle_weight',
    'Peso bruto total homologado',
    'Homologated gross vehicle weight.',
    'NUMBER',
    'kg',
  ),
  attribute(
    'gross_combination_weight',
    'Peso bruto total combinado',
    'Gross combined vehicle weight.',
    'NUMBER',
    'kg',
  ),
  attribute(
    'wading_depth',
    'Capacidade de imersão',
    'Maximum manufacturer-reported wading depth.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'top_speed',
    'Velocidade máxima',
    'Manufacturer-reported maximum speed.',
    'NUMBER',
    'km/h',
  ),
  attribute(
    'acceleration_0_100',
    'Aceleração de 0 a 100 km/h',
    'Manufacturer-reported 0–100 km/h time.',
    'NUMBER',
    's',
  ),
  attribute(
    'battery_usable_capacity',
    'Capacidade útil da bateria',
    'Usable high-voltage battery capacity.',
    'NUMBER',
    'kWh',
  ),
  attribute(
    'electric_range_inmetro',
    'Autonomia Inmetro',
    'Electric range under the Brazilian Inmetro cycle.',
    'NUMBER',
    'km',
  ),
  attribute(
    'electric_range_wltp',
    'Autonomia WLTP',
    'Electric range under the WLTP cycle.',
    'NUMBER',
    'km',
  ),
  attribute(
    'electric_range_unspecified',
    'Autonomia sem ciclo identificado',
    'Electric range reported without an identified test cycle.',
    'NUMBER',
    'km',
  ),
  attribute(
    'dc_charge_power',
    'Potência máxima de recarga CC',
    'Maximum direct-current charging power.',
    'NUMBER',
    'kW',
  ),
  attribute(
    'ac_charge_power',
    'Potência máxima de recarga CA',
    'Maximum alternating-current charging power.',
    'NUMBER',
    'kW',
  ),
  attribute(
    'front_cargo_volume',
    'Volume do compartimento dianteiro',
    'Front luggage-compartment volume.',
    'NUMBER',
    'L',
  ),
  attribute(
    'torque_max_kgfm',
    'Torque máximo',
    'Maximum manufacturer-reported torque in kilogram-force metres.',
    'NUMBER',
    'kgf.m',
  ),
  attribute(
    'body_style',
    'Carroceria',
    'Manufacturer body or roof-and-length code.',
    'TEXT',
  ),
  attribute(
    'tire_spec',
    'Pneus',
    'Manufacturer-reported tire specification.',
    'TEXT',
  ),
  attribute(
    'wheel_spec',
    'Rodas',
    'Manufacturer-reported wheel specification.',
    'TEXT',
  ),
  attribute(
    'rear_suspension',
    'Suspensão traseira',
    'Manufacturer-reported rear suspension.',
    'TEXT',
  ),
  attribute(
    'front_suspension',
    'Suspensão dianteira',
    'Manufacturer-reported front suspension.',
    'TEXT',
  ),
  attribute(
    'front_overhang',
    'Balanço dianteiro',
    'Front overhang.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'rear_overhang',
    'Balanço traseiro',
    'Rear overhang.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'length_with_extension',
    'Comprimento com extensão',
    'Overall length including the manufacturer-specified frame extension.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'cargo_area_length',
    'Comprimento da zona de carga',
    'Usable cargo-area length.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'cargo_area_width',
    'Largura da zona de carga',
    'Usable cargo-area width.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'cargo_area_height',
    'Altura da zona de carga',
    'Usable cargo-area height.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'side_door_width',
    'Largura do vão da porta lateral',
    'Side cargo-door opening width.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'side_door_height',
    'Altura do vão da porta lateral',
    'Side cargo-door opening height.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'rear_door_width',
    'Largura do vão da porta traseira',
    'Rear cargo-door opening width.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'rear_door_height',
    'Altura do vão da porta traseira',
    'Rear cargo-door opening height.',
    'NUMBER',
    'mm',
  ),
  attribute(
    'standard_features',
    'Equipamentos de série',
    'Complete manufacturer-reported standard-equipment list for the configuration.',
    'LIST',
  ),
  attribute(
    'exterior_features',
    'Equipamentos externos',
    'Manufacturer-reported exterior equipment.',
    'LIST',
  ),
  attribute(
    'interior_features',
    'Equipamentos internos',
    'Manufacturer-reported interior equipment.',
    'LIST',
  ),
  attribute(
    'safety_features',
    'Equipamentos de segurança',
    'Manufacturer-reported safety equipment.',
    'LIST',
  ),
  attribute(
    'technology_features',
    'Tecnologia e conveniência',
    'Manufacturer-reported technology and convenience equipment.',
    'LIST',
  ),
  attribute(
    'multimedia_features',
    'Sistema multimídia',
    'Manufacturer-reported multimedia equipment.',
    'LIST',
  ),
  attribute(
    'exterior_colors',
    'Cores externas',
    'Manufacturer-reported exterior colors.',
    'LIST',
  ),
  attribute(
    'adaptive_cruise',
    'Piloto automático adaptativo',
    'Adaptive cruise-control availability.',
    'AVAILABILITY',
  ),
  attribute(
    'camera_360',
    'Câmera 360°',
    'Surround-view camera availability.',
    'AVAILABILITY',
  ),
  attribute(
    'stability_control',
    'Controle de estabilidade',
    'Electronic stability-control availability.',
    'AVAILABILITY',
  ),
  attribute('sunroof', 'Teto solar', 'Sunroof availability.', 'AVAILABILITY'),
  attribute(
    'reference_price',
    'Preço de referência (sem data de vigência)',
    'Public list price observed on the official comparison page.',
    'NUMBER',
    'BRL',
  ),
  attribute(
    'damper_modes',
    'Modos de amortecedor',
    'Selectable damper (shock-absorber) modes reported by the manufacturer.',
    'LIST',
  ),
  attribute(
    'steering_modes',
    'Modos de direção',
    'Selectable steering-assist modes reported by the manufacturer.',
    'LIST',
  ),
  attribute(
    'exhaust_modes',
    'Modos de escapamento',
    'Selectable exhaust-sound modes reported by the manufacturer.',
    'LIST',
  ),
  attribute(
    'paddle_shifters',
    'Paddle shifters',
    'Steering-wheel gearshift paddles availability.',
    'AVAILABILITY',
  ),
  attribute(
    'headlights',
    'Faróis',
    'Manufacturer-reported headlight technology.',
    'TEXT',
  ),
  attribute(
    'shock_absorbers',
    'Amortecedores',
    'Manufacturer-reported shock-absorber specification when the source does not split it by axle.',
    'TEXT',
  ),
];

const attributeByCode = new Map(attributes.map((item) => [item.code, item]));
const display = (value) =>
  Array.isArray(value) ? value.join('; ') : String(value);
const specification = (sourceKey, code, value, options = {}) => {
  const definition = attributeByCode.get(code);
  const rawValue = options.rawValue ?? `${definition.label}: ${display(value)}`;
  const result = {
    attribute: code,
    source: sourceKey,
    locator: options.locator ?? 'Official technical specifications table',
    excerpt: options.excerpt ?? rawValue,
    rawValue,
    qualifiers: options.qualifiers ?? {},
  };
  if (definition.valueType === 'AVAILABILITY') result.availability = value;
  else result.value = value;
  return result;
};

const specs = (sourceKey, values, locator) =>
  Object.entries(values).map(([code, value]) =>
    specification(sourceKey, code, value, { locator }),
  );

const config = (
  name,
  modelYear,
  identitySource,
  specifications,
  options = {},
) => ({
  name,
  market: 'BR',
  modelYear,
  identity: {
    source: identitySource,
    locator: options.identityLocator ?? 'Official model/version listing',
    excerpt: options.identityExcerpt ?? name,
    note:
      options.identityNote ??
      `Current Ford Brasil configuration verified on ${capturedOn}; source terminology is preserved.`,
  },
  specifications,
});

const commonCommercialFeatures = [
  'SYNC 4 com tela touchscreen de 12 polegadas',
  'Android Auto e Apple CarPlay sem fio',
  'Bluetooth',
  'Entradas USB',
  'Direção elétrica',
  'Controle eletrônico de estabilidade',
  'Assistente de frenagem autônoma',
  'Sensor de estacionamento dianteiro e traseiro',
  'FordPass Connect',
];

const rangerXlFeatures = [
  '7 airbags: frontais, laterais, cortinas e joelho do motorista',
  'Controle eletrônico de estabilidade com ABS e EBD',
  'Assistente de partida em rampas',
  'Controle automático em descidas',
  'Diferencial traseiro blocante',
  'Direção elétrica',
  'Piloto automático',
  'SYNC 4 com tela touchscreen de 10 polegadas',
  'Android Auto e Apple CarPlay sem fio',
  'FordPass Pro',
];

const rangerXlRows = [
  [
    'XL 2.0 CH Diesel 4x4 MT',
    2027,
    'Manual de 6 velocidades',
    1849,
    1371,
    1880,
    null,
    248600,
  ],
  [
    'XL 2.0 CH Diesel 4x4 AT',
    2027,
    'Automática de 6 velocidades',
    1872,
    1318,
    1880,
    null,
    258600,
  ],
  [
    'XL 2.0 CS Diesel 4x4 MT',
    2027,
    'Manual de 6 velocidades',
    1997,
    1223,
    1880,
    1790,
    256600,
  ],
  [
    'XL 2.0 CS Diesel 4x4 AT',
    2027,
    'Automática de 6 velocidades',
    2020,
    1170,
    1880,
    1790,
    266600,
  ],
  [
    'XL 2.0 CD Diesel 4x4 MT',
    2026,
    'Manual de 6 velocidades',
    2123,
    1097,
    1884,
    1230,
    272600,
  ],
  [
    'XL 2.0 CD Diesel 4x4 AT',
    2027,
    'Automática de 6 velocidades',
    2130,
    1060,
    1884,
    1230,
    282600,
  ],
];

const rangerXlConfigurations = rangerXlRows.map(
  ([
    name,
    year,
    transmission,
    curbWeight,
    payload,
    height,
    cargoBedVolume,
    price,
  ]) =>
    config(
      name,
      year,
      'ranger_compare',
      [
        ...specs(
          'ranger_xl_pdf',
          {
            engine: '2.0 Turbo Diesel',
            displacement: 1995,
            power_max: 170,
            torque_max: 405,
            fuel_type: ['DIESEL'],
            transmission,
            drivetrain: '4x4',
            length: 5370,
            height,
            width_with_mirrors: 2208,
            wheelbase: 3270,
            curb_weight: curbWeight,
            payload,
            wading_depth: 800,
            fuel_tank: 80,
            tire_spec: '255/70 R16 All Terrain',
            wheel_spec: 'Aço estampado 16 polegadas',
            stability_control: 'STANDARD',
            standard_features: rangerXlFeatures,
          },
          'Technical specifications and standard-equipment tables',
        ),
        ...(cargoBedVolume == null
          ? []
          : specs(
              'ranger_xl_pdf',
              { cargo_bed_volume: cargoBedVolume },
              'Dimensions and capacities table',
            )),
        ...specs(
          'ranger_compare',
          { reference_price: price },
          `Version card: ${name} ${year}`,
        ),
      ],
      {
        identityExcerpt: `${name} ${year}`,
        identityLocator: 'Official Ranger version comparison cards',
      },
    ),
);

const rangerRetailRows = [
  {
    name: 'XLS 2.0 Diesel 4x4 AT',
    price: 285900,
    engine: '2.0 Turbo Diesel',
    power: 170,
    torque: 405,
    transmission: 'Automática de 6 velocidades',
    drivetrain: '4x4',
    modes: ['Normal', 'Eco', 'Rebocar/Transportar', 'Escorregadio'],
    features: [
      'Carregador por indução',
      'Câmera de ré',
      'Degrau de acesso à caçamba',
      'Diferencial traseiro blocante',
      'Rodas de liga leve 17 polegadas',
      'SYNC 4 com tela de 10 polegadas',
    ],
  },
  {
    name: 'Black 2.0L 4x2 AT Diesel',
    price: 242600,
    engine: '2.0 Turbo Diesel',
    power: 170,
    torque: 405,
    transmission: 'Automática de 6 velocidades',
    drivetrain: '4x2',
    modes: ['Normal', 'Eco', 'Rebocar/Transportar', 'Escorregadio'],
    features: [
      'Carregador por indução',
      'Estribos laterais',
      'Faróis Full LED',
      'Rodas de liga leve 18 polegadas',
      'Santo Antônio esportivo',
      'SYNC 4 com tela de 10 polegadas',
    ],
  },
  {
    name: 'XLS 3.0 V6 Diesel 4WD AT',
    price: 309600,
    engine: '3.0 V6 Turbo Diesel',
    power: 250,
    torque: 600,
    transmission: 'Automática de 10 velocidades',
    drivetrain: '4WD',
    modes: ['Normal', 'Eco', 'Rebocar/Transportar', 'Escorregadio'],
    features: [
      'Carregador por indução',
      'Degrau de acesso à caçamba',
      'Faróis Full LED',
      'Freios a disco nas quatro rodas',
      'Rodas de liga leve 17 polegadas',
      'SYNC 4 com tela de 10 polegadas',
    ],
  },
  {
    name: 'XLT 3.0 V6 Diesel 4WD AT',
    price: 315900,
    engine: '3.0 V6 Turbo Diesel',
    power: 250,
    torque: 600,
    transmission: 'Automática de 10 velocidades',
    drivetrain: '4WD',
    modes: ['Normal', 'Eco', 'Rebocar/Transportar', 'Escorregadio'],
    features: [
      'Assistente autônomo de frenagem com detecção de pedestres',
      'Bancos com revestimento premium',
      'Farol alto automático',
      'Reconhecimento de sinais de trânsito',
      'Trava elétrica da tampa da caçamba',
      'SYNC 4 com tela de 10 polegadas',
    ],
  },
  {
    name: 'Limited 3.0 V6 Diesel 4WD AT',
    price: 346900,
    engine: '3.0 V6 Turbo Diesel',
    power: 250,
    torque: 600,
    transmission: 'Automática de 10 velocidades',
    drivetrain: '4WD',
    modes: [
      'Normal',
      'Eco',
      'Rebocar/Transportar',
      'Escorregadio',
      'Lama/Terra',
      'Areia',
    ],
    features: [
      'Ar-condicionado automático digital de duas zonas',
      'Assistente autônomo de frenagem com detecção de pedestres',
      'Bancos com revestimento premium',
      'Chave presencial e partida sem chave',
      'Freio de mão eletrônico',
      'Navegador off-road',
      'Rodas de liga leve 18 polegadas',
      'SYNC 4 com tela de 12 polegadas',
    ],
  },
  {
    name: 'Limited 3.0 V6 Diesel 4WD AT + Kit Opcional',
    price: 372900,
    engine: '3.0 V6 Turbo Diesel',
    power: 250,
    torque: 600,
    transmission: 'Automática de 10 velocidades',
    drivetrain: '4WD',
    modes: [
      'Normal',
      'Eco',
      'Rebocar/Transportar',
      'Escorregadio',
      'Lama/Terra',
      'Areia',
    ],
    features: [
      'Alerta de tráfego cruzado em marcha ré',
      'Frenagem autônoma em marcha ré com detecção de pedestres',
      'Assistente de manobras evasivas',
      'Assistente de permanência e centralização em faixa',
      'Assistente em cruzamentos',
      'Câmera 360 graus',
      'Painel digital de 12,4 polegadas',
      'Piloto automático adaptativo com Stop & Go',
      'Rodas de liga leve 20 polegadas',
      'Monitoramento de ponto cego BLIS',
    ],
  },
];

const rangerRetailConfigurations = rangerRetailRows.map((row) =>
  config(
    row.name,
    2027,
    'ranger_compare',
    specs(
      'ranger_compare',
      {
        engine: row.engine,
        power_max: row.power,
        torque_max: row.torque,
        fuel_type: ['DIESEL'],
        transmission: row.transmission,
        drivetrain: row.drivetrain,
        driving_modes: row.modes,
        length: 5370,
        height: 1884,
        width_with_mirrors: 2208,
        wheelbase: 3270,
        fuel_tank: 80,
        wading_depth: 800,
        reference_price: row.price,
        standard_features: row.features,
      },
      `Official version card and current Ranger technical sheet: ${row.name} 2027`,
    ),
    {
      identityExcerpt: `${row.name} 2027`,
      identityLocator: 'Official Ranger version comparison cards',
    },
  ),
);

const rangerRaptorExteriorFeatures = [
  'Ajuste elétrico da altura dos faróis',
  'Estribo plataforma',
  'Faróis de neblina em LED',
  'Faróis Matrix LED',
  'Grade do radiador ativa',
  'Grade Raptor',
  'Iluminação 360°',
  'Iluminação na caçamba',
  'Lanternas traseiras em LED do DRL',
  'Luzes de condução diurna (DRL)',
  'Moldura de para-lamas na cor preta',
  'Para-barros dianteiros',
  'Para-barros traseiros',
  'Para-choque na cor preta',
  'Pneus 285/70 R17 General Grabber',
  'Protetor de caçamba',
  'Protetor off-road dianteiro',
  'Protetores inferiores off-road',
  'Retrovisores externos com ajuste elétrico, indicador de direção, rebatimento elétrico, aquecimento dos retrovisores e luz de cortesia',
  'Rodas de liga leve 17”',
  'Tampa traseira com assistente de abertura e fechamento',
  'Tomada 120V na caçamba',
  'Visual Raptor',
];

const rangerRaptorInteriorFeatures = [
  '6 interruptores auxiliares',
  'Ajuste elétrico do banco do motorista em 10 posições e passageiro em 8 posições',
  'Aquecimento dos bancos',
  'Bancos exclusivos Raptor com revestimento premium',
  'Chave com sensor de presença e partida sem chave',
  'Compartimento extra sob o banco traseiro',
  'Descansa braço traseiro',
  'Paddle Shifters',
  'Painel de instrumentos colorido Raptor, configurável através de comandos no volante (12.4”)',
  'Pontos de amarração de carga (6)',
  'Retrovisor eletrocrômico',
  'Sensor de chuva',
  'Tomada 120V',
  'Vidros elétricos dianteiros/traseiros com sistema global de abertura/fechamento com um toque para cima/baixo e antiesmagamento para o motorista e passageiros',
  'Volante com ajuste de altura e profundidade',
  'Volante Raptor com revestimento premium',
];

const rangerRaptorMultimediaFeatures = [
  'AppLink',
  'Assistência de emergência',
  'Premium Sound System by Bang & Olufsen (8 alto-falantes)',
  'Bluetooth',
  'Comando de voz em português',
  'Comandos de áudio no volante',
  'Conectividade Android Auto™ e Apple CarPlay™ sem fio',
  'Entradas USB',
  'Navegador GPS integrado',
  'Navegador Off-Road',
  'Tela central multifuncional touch screen HD',
];

const rangerRaptorSafetyFeatures = [
  'Airbags (7): frontais, laterais, cortinas e joelho para o motorista',
  'Alarme perimétrico',
  'Alerta de colisão com aviso luminoso e sonoro no painel de instrumentos',
  'Alerta de tráfego cruzado em marcha à ré',
  'Assistente autônomo de frenagem (com detecção de pedestres)',
  'Assistente autônomo de frenagem em marcha à ré (com detecção de pedestres)',
  'Assistente de manobras evasivas',
  'Assistente de partida em rampas',
  'Assistente de permanência e centralização em faixa',
  'Câmera 360°',
  'Cintos de segurança traseiros laterais e central de 3 pontos',
  'Controle eletrônico de estabilidade',
  'Farol alto automático',
  'Frenagem pós-colisão',
  'Limitador de velocidade',
  'Piloto automático adaptativo (ACC) com Stop & Go',
  'Piloto automático off-road (Trail Control)',
  'Sensor de estacionamento dianteiro',
  'Sensor de estacionamento traseiro',
  'Sistema de monitoramento de ponto cego (BLIS)',
  'Trava elétrica da tampa da caçamba',
];

const rangerRaptorTechnologyFeatures = [
  '3 modos de amortecedor selecionáveis – Normal, Sport e Off-Road',
  '4 modos de direção selecionáveis – Normal, Conforto, Sport, Off-Road',
  '4 modos de escapamento selecionáveis – Silencioso, Normal, Sport, Baja',
  '7 modos de condução selecionáveis – Normal, Esportivo, Escorregadio, Lama/Terra, Areia, Baja, Rock Crawl',
  'Câmbio eletrônico (E-Shifter)',
  'Direção elétrica ajustável',
  'Pro Trailer assistente de reboque',
  'Sensor de monitoramento de pressão dos pneus (TPMS)',
  'Start & Stop',
];

const rangerRaptorFeatures = [
  'Diferencial dianteiro blocante',
  'Diferencial traseiro blocante',
  'Suspensão FOX 2.5 Live Valve Racing',
  'Faróis Matrix LED',
  'Câmera 360 graus',
  'Piloto automático adaptativo com Stop & Go',
  'Piloto automático off-road Trail Control',
  'SYNC 4 com navegador off-road',
  'Sistema de som Bang & Olufsen com 8 alto-falantes',
  '7 airbags',
];

const maverickFeatures = [
  '7 airbags',
  'Assistente de frenagem autônoma com detecção de pedestres e ciclistas',
  'Piloto automático adaptativo com Stop & Go',
  'Câmera 360 graus',
  'Monitoramento de ponto cego BLIS com tráfego cruzado',
  'SYNC 4 com tela de 13,2 polegadas',
  'Sistema de som Bang & Olufsen com 8 alto-falantes',
  'Teto solar',
];

const maverickRows = [
  [
    'Black',
    253,
    380,
    '2.0L Turbo EcoBoost GTDi',
    ['GASOLINE'],
    'Automática de 8 velocidades',
    'AWD Inteligente',
    1733,
    3077,
    1759,
    618,
    62.4,
    '225/65 R17 AT',
    219900,
    ['Normal', 'Escorregadio', 'Eco', 'Esportivo', 'Rebocar/Transportar'],
  ],
  [
    'Tremor',
    253,
    380,
    '2.0L Turbo EcoBoost GTDi',
    ['GASOLINE'],
    'Automática de 8 velocidades',
    '4WD',
    1758,
    3075,
    1832,
    550,
    62.4,
    '235/65 R17 AT+',
    239900,
    [
      'Normal',
      'Escorregadio',
      'Eco',
      'Off-Road',
      'Esportivo',
      'Rebocar/Transportar',
    ],
  ],
  [
    'Hybrid',
    194,
    210,
    '2.5L Atkinson FHEV',
    ['GASOLINE', 'ELECTRICITY'],
    'eCVT',
    'AWD Inteligente',
    1733,
    3077,
    1829,
    584,
    52.2,
    '225/55 R19',
    239900,
    ['Normal', 'Escorregadio', 'Eco', 'Esportivo', 'Rebocar/Transportar'],
  ],
];

const maverickConfigurations = maverickRows.map(
  ([
    name,
    power,
    torque,
    engine,
    fuel,
    transmission,
    drivetrain,
    height,
    wheelbase,
    curbWeight,
    payload,
    fuelTank,
    tires,
    price,
    modes,
  ]) =>
    config(
      name,
      2026,
      'maverick_compare',
      [
        ...specs(
          'maverick_pdf',
          {
            engine,
            power_max: power,
            torque_max: torque,
            fuel_type: fuel,
            transmission,
            drivetrain,
            driving_modes: modes,
            length: 5096,
            height,
            width_with_mirrors: 2122,
            width_without_mirrors: 1979,
            wheelbase,
            curb_weight: curbWeight,
            payload,
            fuel_tank: fuelTank,
            passenger_capacity: 5,
            cargo_bed_volume: 943,
            tire_spec: tires,
            adaptive_cruise: 'STANDARD',
            camera_360: 'STANDARD',
            stability_control: 'STANDARD',
            sunroof: 'STANDARD',
            standard_features: maverickFeatures,
          },
          `Maverick ${name} column in the technical and standard-equipment tables`,
        ),
        ...specs(
          'maverick_compare',
          { reference_price: price },
          `Official Maverick ${name} comparison card`,
        ),
      ],
      {
        identityExcerpt: `Maverick ${name}`,
        identityLocator:
          'Official Maverick comparison cards; current 2026 owner-manual coverage',
        identityNote: `Current Ford Brasil Maverick ${name} configuration. The comparison page omits model year; 2026 is supported by the current manual coverage and the 9/2026 catalog context.`,
      },
    ),
);

const f150Features = [
  '8 airbags',
  'Piloto automático adaptativo com Stop & Go',
  'Monitoramento de ponto cego BLIS com cobertura de reboque',
  'Assistente autônomo de frenagem com detecção de pedestres',
  'Câmera 360 graus',
  'Pro Trailer assistente de reboque',
  'SYNC 4 com tela de 12 polegadas',
  'Sistema de som Bang & Olufsen com 14 alto-falantes',
  'Teto solar panorâmico',
];

const f150Rows = [
  [
    'Lariat',
    5894,
    1958,
    3694,
    2481,
    740,
    3492,
    '275/60 R20 AT',
    'Liga leve 20 polegadas cromada',
    560000,
  ],
  [
    'Lariat Black',
    5894,
    1958,
    3694,
    2481,
    740,
    3492,
    '275/60 R20 AT',
    'Liga leve 20 polegadas escurecida',
    560000,
  ],
  [
    'Tremor',
    5880,
    2015,
    3698,
    2550,
    671,
    3945,
    '275/70 R18 AT',
    'Liga leve 18 polegadas escurecida',
    580000,
  ],
];

const f150Configurations = f150Rows.map(
  ([
    name,
    length,
    height,
    wheelbase,
    curbWeight,
    payload,
    towing,
    tires,
    wheels,
    price,
  ]) =>
    config(
      name,
      2026,
      'f150_compare',
      [
        ...specs(
          'f150_pdf',
          {
            engine: 'Coyote 5.0L V8',
            power_max: 405,
            torque_max: 556,
            fuel_type: ['GASOLINE'],
            transmission: 'Automática de 10 velocidades',
            drivetrain: '4x4 integral',
            driving_modes: [
              'Normal',
              'Esportivo',
              'Rebocar/Transportar',
              'Escorregadio',
              'Trilha',
              'Off-Road',
              'Eco',
            ],
            length,
            height,
            width_with_mirrors: 2430,
            wheelbase,
            curb_weight: curbWeight,
            payload,
            towing_capacity: towing,
            fuel_tank: 136,
            passenger_capacity: 5,
            cargo_bed_volume: 1495,
            tire_spec: tires,
            wheel_spec: wheels,
            adaptive_cruise: 'STANDARD',
            camera_360: 'STANDARD',
            stability_control: 'STANDARD',
            sunroof: 'STANDARD',
            standard_features: f150Features,
          },
          `F-150 ${name === 'Lariat' ? 'Lariat Chrome' : name} column in the current technical sheet`,
        ),
        ...specs(
          'f150_compare',
          { reference_price: price },
          `Official F-150 ${name} comparison card`,
        ),
      ],
      {
        identityExcerpt: name,
        identityLocator: 'Official F-150 comparison cards',
        identityNote:
          name === 'Lariat'
            ? 'Current Ford Brasil F-150 Lariat; the current technical sheet calls this configuration Lariat Chrome.'
            : `Current Ford Brasil F-150 ${name}; the comparison page omits model year and the current technical sheet is published under the 2026 asset path.`,
      },
    ),
);

const modelsPartOne = [
  {
    name: 'Ranger',
    configurations: [...rangerXlConfigurations, ...rangerRetailConfigurations],
  },
  {
    name: 'Ranger Raptor',
    configurations: [
      config(
        'Raptor 3.0 V6 Bi-turbo 4WD AT',
        2026,
        'ranger_raptor_page',
        [
          ...specs(
            'ranger_raptor_pdf',
            {
              engine: '3.0L V6 Bi-turbo',
              power_max: 397,
              torque_max: 583,
              fuel_type: ['GASOLINE'],
              transmission: 'Automática de 10 velocidades',
              drivetrain: '4WD',
              driving_modes: [
                'Normal',
                'Esportivo',
                'Escorregadio',
                'Lama/Terra',
                'Areia',
                'Baja',
                'Rock Crawl',
              ],
              length: 5381,
              height: 1922,
              width_with_mirrors: 2208,
              wheelbase: 3270,
              curb_weight: 2415,
              payload: 715,
              wading_depth: 850,
              fuel_tank: 77,
              tire_spec: '285/70 R17 General Grabber',
              wheel_spec: 'Liga leve 17 polegadas',
              adaptive_cruise: 'STANDARD',
              camera_360: 'STANDARD',
              stability_control: 'STANDARD',
              standard_features: rangerRaptorFeatures,
            },
            'Performance off-road, dimensions and standard-equipment tables',
          ),
          ...specs(
            'ranger_raptor_pdf',
            {
              damper_modes: ['Normal', 'Sport', 'Off-Road'],
              steering_modes: ['Normal', 'Conforto', 'Sport', 'Off-Road'],
              exhaust_modes: ['Silencioso', 'Normal', 'Sport', 'Baja'],
              paddle_shifters: 'STANDARD',
              headlights: 'Matrix LED',
              shock_absorbers: 'FOX 2.5” Live Valve Racing',
            },
            'Technology, interior, exterior and performance off-road tables (page 2)',
          ),
          ...specs(
            'ranger_raptor_pdf',
            {
              exterior_features: rangerRaptorExteriorFeatures,
              interior_features: rangerRaptorInteriorFeatures,
              multimedia_features: rangerRaptorMultimediaFeatures,
              safety_features: rangerRaptorSafetyFeatures,
              technology_features: rangerRaptorTechnologyFeatures,
            },
            'Standard-equipment tables (page 2)',
          ),
          ...specs(
            'ranger_raptor_page',
            { reference_price: 499000 },
            'Version page price card: Raptor 3.0 V6 Bi-turbo 4WD AT 2026 (AOD6)',
          ),
        ],
        {
          identityExcerpt: 'Ranger Raptor 2026 (AOD6)',
          identityLocator: 'Official version page',
        },
      ),
    ],
  },
  { name: 'Maverick', configurations: maverickConfigurations },
  { name: 'F-150', configurations: f150Configurations },
];

const territoryFeatures = [
  '6 airbags',
  'Piloto automático adaptativo com Stop & Go',
  'Assistente autônomo de frenagem com detecção de pedestres',
  'Assistente de permanência e centralização em faixa',
  'Monitoramento de ponto cego com alerta de tráfego cruzado',
  'Câmera 360 graus',
  'SYNC Touch com tela de 12,3 polegadas',
  'Painel digital de 12 polegadas',
  'Teto solar panorâmico',
];

const territoryConfigurations = [
  config(
    'Titanium',
    2026,
    'territory_page',
    specs(
      'territory_pdf',
      {
        engine: '1.5L Turbo EcoBoost',
        power_max: 169,
        torque_max: 250,
        fuel_type: ['GASOLINE'],
        transmission:
          'Automática DCT de 7 velocidades com dupla embreagem banhada a óleo',
        drivetrain: 'Dianteira',
        driving_modes: ['Normal', 'Eco', 'Esportivo', 'Trilha'],
        length: 4685,
        height: 1706,
        width_with_mirrors: 2177,
        width_without_mirrors: 1935,
        wheelbase: 2726,
        curb_weight: 1705,
        luggage_volume: 448,
        luggage_volume_seats_folded: 1422,
        fuel_tank: 60,
        passenger_capacity: 5,
        tire_spec: '235/50 R19',
        wheel_spec: 'Liga leve 19 polegadas',
        adaptive_cruise: 'STANDARD',
        camera_360: 'STANDARD',
        stability_control: 'STANDARD',
        sunroof: 'STANDARD',
        standard_features: territoryFeatures,
      },
      'Titanium technical specifications and standard-equipment tables',
    ),
    {
      identityExcerpt: 'Territory Titanium 2026',
      identityLocator: 'Official Territory Titanium version page',
    },
  ),
];

const broncoFeatures = [
  '9 airbags',
  'Piloto automático adaptativo com Stop & Go',
  'Assistente autônomo de frenagem com detecção de pedestres',
  'Assistente de permanência e centralização em faixa',
  'Monitoramento de ponto cego BLIS',
  'Câmera 360 graus com visualização off-road',
  'Diferencial traseiro blocante',
  'Trail Control',
  'SYNC 4 com tela de 13,2 polegadas',
  'Teto solar elétrico',
];

const broncoConfigurations = [
  config(
    'Badlands 26.5MY',
    2026,
    'bronco_sport_page',
    specs(
      'bronco_sport_pdf',
      {
        engine: '2.0L Turbo EcoBoost GTDi',
        power_max: 253,
        torque_max: 380,
        fuel_type: ['GASOLINE'],
        transmission: 'Automática de 8 velocidades',
        drivetrain: '4x4',
        driving_modes: [
          'Normal',
          'Eco',
          'Esportivo',
          'Escorregadio',
          'Off-Road',
          'Areia',
          'Rock Crawl',
        ],
        length: 4420,
        height: 1814,
        width_with_mirrors: 2087,
        width_without_mirrors: 1888,
        wheelbase: 2670,
        curb_weight: 1794,
        payload: 433,
        towing_capacity: 1000,
        luggage_volume: 580,
        luggage_volume_seats_folded: 1472,
        fuel_tank: 59.5,
        passenger_capacity: 5,
        tire_spec: '225/65 R17 All Terrain',
        wheel_spec: 'Liga leve 17 polegadas',
        adaptive_cruise: 'STANDARD',
        camera_360: 'STANDARD',
        stability_control: 'STANDARD',
        sunroof: 'STANDARD',
        standard_features: broncoFeatures,
      },
      'Badlands 26.5MY technical specifications and standard-equipment tables',
    ),
    {
      identityExcerpt: 'Bronco Sport Badlands 26.5MY',
      identityLocator: 'Official Bronco Sport version page',
    },
  ),
];

const machEFeatures = [
  '7 airbags',
  'Piloto automático adaptativo com Stop & Go',
  'Assistente autônomo de frenagem com detecção de pedestres e ciclistas',
  'Assistente de permanência e centralização em faixa',
  'Monitoramento de ponto cego BLIS',
  'Câmera 360 graus',
  'SYNC 4A com tela vertical de 15,5 polegadas',
  'Sistema de som Bang & Olufsen com 10 alto-falantes',
  'Teto panorâmico fixo',
];

const machEConfigurations = [
  config(
    'GT Performance',
    2025,
    'mustang_mach_e_page',
    specs(
      'mustang_mach_e_pdf',
      {
        engine: 'Dois motores elétricos',
        power_max: 487,
        torque_max: 860,
        fuel_type: ['ELECTRICITY'],
        transmission: 'Automática de uma velocidade',
        drivetrain: 'eAWD',
        driving_modes: ['Whisper', 'Engage', 'Unbridle'],
        length: 4743,
        height: 1613,
        width_with_mirrors: 2097,
        width_without_mirrors: 1930,
        wheelbase: 2985,
        curb_weight: 2307,
        payload: 412,
        luggage_volume: 402,
        front_cargo_volume: 139,
        battery_usable_capacity: 91,
        electric_range_inmetro: 379,
        electric_range_unspecified: 541,
        dc_charge_power: 150,
        ac_charge_power: 11,
        acceleration_0_100: 3.7,
        passenger_capacity: 5,
        tire_spec: '245/45 R20',
        wheel_spec: 'Liga leve 20 polegadas',
        adaptive_cruise: 'STANDARD',
        camera_360: 'STANDARD',
        stability_control: 'STANDARD',
        sunroof: 'STANDARD',
        standard_features: machEFeatures,
      },
      'GT Performance technical specifications and standard-equipment tables',
    ),
    {
      identityExcerpt: 'Mustang Mach-E GT Performance',
      identityLocator:
        'Official current-sale version page and 2025 technical sheet',
      identityNote:
        'Current Ford Brasil Mustang Mach-E GT Performance. The current sale page does not state a newer model year; the authoritative technical sheet identifies model year 2025.',
    },
  ),
];

const darkHorseFeatures = [
  '6 airbags',
  'Piloto automático adaptativo',
  'Assistente autônomo de frenagem com detecção de pedestres',
  'Assistente de permanência em faixa',
  'Suspensão adaptativa MagneRide',
  'Freios Brembo de alta performance',
  'Diferencial traseiro Torsen',
  'Freio de drift eletrônico',
  'SYNC 4 com tela de 13,2 polegadas',
  'Painel digital de 12,4 polegadas',
];

const darkHorseConfigurations = [
  config(
    'Dark Horse',
    2025,
    'mustang_dark_horse_page',
    specs(
      'mustang_dark_horse_pdf',
      {
        engine: 'Coyote 5.0L V8',
        power_max: 507,
        torque_max: 567,
        fuel_type: ['GASOLINE'],
        transmission: 'Automática de 10 velocidades',
        drivetrain: 'Traseira',
        driving_modes: [
          'Normal',
          'Esportivo',
          'Escorregadio',
          'Pista',
          'Pista Drag',
        ],
        length: 4821,
        height: 1403,
        width_with_mirrors: 2080,
        width_without_mirrors: 1958,
        wheelbase: 2719,
        curb_weight: 1832,
        payload: 350,
        passenger_capacity: 4,
        tire_spec: '255/40 R19 dianteiros; 275/40 R19 traseiros',
        wheel_spec: 'Liga leve 19 polegadas',
        adaptive_cruise: 'STANDARD',
        stability_control: 'STANDARD',
        standard_features: darkHorseFeatures,
      },
      'Dark Horse technical specifications and standard-equipment tables',
    ),
    {
      identityExcerpt: 'Mustang Dark Horse 2025',
      identityLocator: 'Official version page and 2025 technical sheet',
    },
  ),
];

const commercialIdentityNote = (model, name) =>
  `Current Ford Brasil ${model} ${name} configuration. The official current comparison and technical-sheet pages omit model year; 2026 is assigned from the current 9/2026 catalog context and the official 2026 asset path.`;

const dieselCommercialBase = {
  engine: '2.0L EcoBlue Turbo Diesel',
  power_max: 165,
  torque_max_kgfm: 39.7,
  fuel_type: ['DIESEL'],
  drivetrain: 'Traseira',
  fuel_tank: 71,
  adblue_tank: 24,
  front_suspension:
    'Independente, com molas helicoidais e barra estabilizadora',
  rear_suspension: 'Eixo rígido com feixes de molas e amortecedores',
  stability_control: 'STANDARD',
};

const commercialConfig = (model, name, identitySource, specSource, values) =>
  config(
    name,
    2026,
    identitySource,
    specs(specSource, values, `${name} technical-specification column`),
    {
      identityExcerpt: name,
      identityLocator: `Official ${model} comparison cards`,
      identityNote: commercialIdentityNote(model, name),
    },
  );

const minibusRows = [
  [
    'Minibus 410L 14+1 MT',
    'L3H2',
    'Manual de 6 velocidades',
    5981,
    2059,
    2547,
    3750,
    1208,
    1564,
    1597,
    3460,
    1740,
    1720,
    11,
    10.2,
    2779,
    4100,
    5500,
    1400,
    1321,
    15,
    '235/65 R16C 121/119R',
  ],
  [
    'Minibus 460E 17+1 MT',
    'L4H3',
    'Manual de 6 velocidades',
    6704,
    2126,
    2781,
    3750,
    1931,
    1564,
    1836,
    4190,
    1740,
    1950,
    15.1,
    14.1,
    3186,
    4600,
    5350,
    750,
    1414,
    18,
    '195/75 R16C 110/108R',
  ],
  [
    'Vidrada 410L L3H2 MT',
    'L3H2',
    'Manual de 6 velocidades',
    5981,
    2059,
    2547,
    3750,
    1208,
    1564,
    1597,
    3494,
    1784,
    1786,
    11,
    10.2,
    2336,
    4100,
    5500,
    1400,
    1764,
    3,
    '235/65 R16C 121/119R',
  ],
  [
    'Vidrada 440E L4H3 MT',
    'L4H3',
    'Manual de 6 velocidades',
    6704,
    2126,
    2781,
    3750,
    1931,
    1564,
    1836,
    4190,
    1740,
    1950,
    15.1,
    14.1,
    2668,
    4400,
    5500,
    1085,
    1747,
    3,
    '195/75 R16C 110/108R',
  ],
  [
    'Minibus 410L 14+1 AT',
    'L3H2',
    'Automática de 10 velocidades',
    5981,
    2059,
    2547,
    3750,
    1208,
    1564,
    1597,
    3460,
    1740,
    1720,
    11,
    10.2,
    2828,
    4100,
    5500,
    1400,
    1272,
    15,
    '235/65 R16C 121/119R',
  ],
  [
    'Minibus 460E 17+1 AT',
    'L4H3',
    'Automática de 10 velocidades',
    6704,
    2126,
    2781,
    3750,
    1931,
    1564,
    1836,
    4190,
    1740,
    1950,
    15.1,
    14.1,
    3244,
    4600,
    5350,
    750,
    1356,
    18,
    '195/75 R16C 110/108R',
  ],
  [
    'Vidrada 410L L3H2 AT',
    'L3H2',
    'Automática de 10 velocidades',
    5981,
    2059,
    2547,
    3750,
    1208,
    1564,
    1597,
    3494,
    1784,
    1786,
    11,
    10.2,
    2376,
    4100,
    5500,
    1400,
    1724,
    3,
    '235/65 R16C 121/119R',
  ],
  [
    'Vidrada 440E L4H3 AT',
    'L4H3',
    'Automática de 10 velocidades',
    6704,
    2126,
    2781,
    3750,
    1931,
    1564,
    1836,
    4190,
    1740,
    1950,
    15.1,
    14.1,
    2724,
    4400,
    5500,
    1085,
    1691,
    3,
    '195/75 R16C 110/108R',
  ],
];

const minibusConfigurations = minibusRows.map(
  ([
    name,
    bodyStyle,
    transmission,
    length,
    width,
    height,
    wheelbase,
    rearOverhang,
    sideDoorHeight,
    rearDoorHeight,
    cargoLength,
    cargoWidth,
    cargoHeight,
    cargoVolume,
    cargoVda,
    curbWeight,
    grossWeight,
    grossCombination,
    towing,
    payload,
    passengers,
    tires,
  ]) =>
    commercialConfig(
      'Transit Minibus',
      name,
      'transit_minibus_compare',
      'transit_minibus_pdf',
      {
        ...dieselCommercialBase,
        transmission,
        body_style: bodyStyle,
        length,
        height,
        width_with_mirrors: 2474,
        width_without_mirrors: width,
        wheelbase,
        front_overhang: 1023,
        rear_overhang: rearOverhang,
        side_door_width: 1200,
        side_door_height: sideDoorHeight,
        rear_door_width: 1520,
        rear_door_height: rearDoorHeight,
        cargo_area_length: cargoLength,
        cargo_area_width: cargoWidth,
        cargo_area_height: cargoHeight,
        cargo_volume: cargoVolume,
        cargo_volume_vda: cargoVda,
        curb_weight: curbWeight,
        gross_vehicle_weight: grossWeight,
        gross_combination_weight: grossCombination,
        towing_capacity: towing,
        towing_capacity_unbraked: 750,
        payload,
        passenger_capacity: passengers,
        tire_spec: tires,
        wheel_spec: 'Aço 16 polegadas',
        standard_features: commonCommercialFeatures,
      },
    ),
);

const furgaoRows = [
  [
    'Furgão 350M L2H3 MT',
    'L2H3',
    'Manual de 6 velocidades',
    5531,
    2771,
    3300,
    3044,
    10.7,
    9.9,
    2246,
    3500,
    2800,
    1254,
  ],
  [
    'Furgão 350L L3H3 MT',
    'L3H3',
    'Manual de 6 velocidades',
    5981,
    2769,
    3750,
    3494,
    12.4,
    11.5,
    2319,
    3500,
    2800,
    1181,
  ],
  [
    'Furgão 380L CARGO L3H3 MT',
    'L3H3',
    'Manual de 6 velocidades',
    5981,
    2769,
    3750,
    3494,
    12.4,
    11.5,
    2319,
    3750,
    2550,
    1431,
  ],
  [
    'Furgão 350M L2H3 AT',
    'L2H3',
    'Automática de 10 velocidades',
    5531,
    2771,
    3300,
    3044,
    10.7,
    9.9,
    2273,
    3500,
    2800,
    1227,
  ],
  [
    'Furgão 350L L3H3 AT',
    'L3H3',
    'Automática de 10 velocidades',
    5981,
    2769,
    3750,
    3494,
    12.4,
    11.5,
    2349,
    3500,
    2800,
    1151,
  ],
  [
    'Furgão 400L CARGO L3H3 AT',
    'L3H3',
    'Automática de 10 velocidades',
    5981,
    2769,
    3750,
    3494,
    12.4,
    11.5,
    2349,
    3995,
    2305,
    1646,
  ],
];

const furgaoConfigurations = furgaoRows.map(
  ([
    name,
    bodyStyle,
    transmission,
    length,
    height,
    wheelbase,
    cargoLength,
    cargoVolume,
    cargoVda,
    curbWeight,
    grossWeight,
    towing,
    payload,
  ]) =>
    commercialConfig(
      'Transit Furgão',
      name,
      'transit_furgao_compare',
      'transit_furgao_pdf',
      {
        ...dieselCommercialBase,
        transmission,
        body_style: bodyStyle,
        length,
        height,
        width_with_mirrors: 2474,
        width_without_mirrors: 2059,
        wheelbase,
        front_overhang: 1023,
        rear_overhang: 1208,
        side_door_width: 1300,
        side_door_height: 1600,
        rear_door_width: 1565,
        rear_door_height: 1887,
        cargo_area_length: cargoLength,
        cargo_area_width: 1784,
        cargo_area_height: 2025,
        cargo_volume: cargoVolume,
        cargo_volume_vda: cargoVda,
        curb_weight: curbWeight,
        gross_vehicle_weight: grossWeight,
        gross_combination_weight: 6300,
        towing_capacity: towing,
        towing_capacity_unbraked: 750,
        payload,
        passenger_capacity: 3,
        tire_spec: '235/65 R16C 121/119R',
        wheel_spec: 'Aço 16 x 6,5 polegadas',
        standard_features: commonCommercialFeatures,
      },
    ),
);

const electricCommercialBase = {
  engine: 'Motor elétrico BorgWarner de 198 kW',
  power_max: 269,
  torque_max_kgfm: 43.8,
  fuel_type: ['ELECTRICITY'],
  transmission: 'Automática de uma velocidade',
  drivetrain: 'Traseira',
  battery_usable_capacity: 68,
  electric_range_inmetro: 193,
  electric_range_wltp: 317,
  dc_charge_power: 115,
  ac_charge_power: 11,
  top_speed: 136,
  gross_vehicle_weight: 3500,
  gross_combination_weight: 3500,
  front_suspension:
    'Independente, com molas helicoidais e barra estabilizadora',
  rear_suspension: 'Independente, com molas helicoidais e barra estabilizadora',
  tire_spec: '235/65 R16C 121/119R',
  wheel_spec: 'Aço 16 x 6,5 polegadas',
  stability_control: 'STANDARD',
};

const eTransitRows = [
  [
    'E-Transit Furgão 350M L2H2',
    'L2H2',
    5531,
    2534,
    3300,
    1208,
    3083,
    1786,
    9.5,
    8.3,
    2649,
    851,
  ],
  [
    'E-Transit Furgão 350M L2H3',
    'L2H3',
    5531,
    2771,
    3300,
    1208,
    3083,
    2025,
    10.7,
    9.9,
    2687,
    813,
  ],
  [
    'E-Transit Furgão 350L L3H2',
    'L3H2',
    5981,
    2530,
    3750,
    1208,
    3533,
    1786,
    11,
    10.2,
    2662,
    838,
  ],
  [
    'E-Transit Furgão 350L L3H3',
    'L3H3',
    5981,
    2769,
    3750,
    1208,
    3533,
    2025,
    12.4,
    11.5,
    2719,
    781,
  ],
  [
    'E-Transit Furgão 350E L4H3',
    'L4H3',
    6704,
    2778,
    3750,
    1931,
    4256,
    2025,
    15.1,
    14.1,
    2836,
    664,
  ],
];

const eTransitConfigurations = eTransitRows.map(
  ([
    name,
    bodyStyle,
    length,
    height,
    wheelbase,
    rearOverhang,
    cargoLength,
    cargoHeight,
    cargoVolume,
    cargoVda,
    curbWeight,
    payload,
  ]) =>
    commercialConfig(
      'E-Transit Furgão',
      name,
      'e_transit_compare',
      'e_transit_pdf',
      {
        ...electricCommercialBase,
        body_style: bodyStyle,
        length,
        height,
        width_with_mirrors: 2474,
        width_without_mirrors: 2059,
        wheelbase,
        front_overhang: 1023,
        rear_overhang: rearOverhang,
        side_door_width: 1300,
        side_door_height: 1600,
        rear_door_width: 1565,
        rear_door_height: 1887,
        cargo_area_length: cargoLength,
        cargo_area_width: 1784,
        cargo_area_height: cargoHeight,
        cargo_volume: cargoVolume,
        cargo_volume_vda: cargoVda,
        curb_weight: curbWeight,
        payload,
        passenger_capacity: 3,
        standard_features: commonCommercialFeatures,
      },
    ),
);

const chassiRows = [
  ['Chassi 350E L4H1 MT', 3500, 3500, 1401],
  ['Chassi 470E L4H1 MT', 4700, 2300, 2601],
];

const chassiConfigurations = chassiRows.map(
  ([name, grossWeight, towing, payload]) =>
    commercialConfig(
      'Transit Chassi',
      name,
      'transit_chassi_compare',
      'transit_chassi_pdf',
      {
        ...dieselCommercialBase,
        transmission: 'Manual de 6 velocidades',
        body_style: 'L4H1',
        length: 6022,
        length_with_extension: 6579,
        height: 2215,
        width_with_mirrors: 2474,
        width_without_mirrors: 2111,
        wheelbase: 3954,
        front_overhang: 1023,
        rear_overhang: 1602,
        curb_weight: 2099,
        gross_vehicle_weight: grossWeight,
        gross_combination_weight: 7000,
        towing_capacity: towing,
        towing_capacity_unbraked: 750,
        payload,
        passenger_capacity: 3,
        tire_spec: '195/75 R16C 110/108R',
        wheel_spec: 'Aço 16 x 6 polegadas',
        standard_features: commonCommercialFeatures,
      },
    ),
);

const modelsPartTwo = [
  { name: 'Territory', configurations: territoryConfigurations },
  { name: 'Bronco Sport', configurations: broncoConfigurations },
  { name: 'Mustang Mach-E', configurations: machEConfigurations },
  { name: 'Mustang Dark Horse', configurations: darkHorseConfigurations },
  { name: 'Transit Minibus', configurations: minibusConfigurations },
  { name: 'Transit Furgão', configurations: furgaoConfigurations },
  { name: 'E-Transit Furgão', configurations: eTransitConfigurations },
  { name: 'Transit Chassi', configurations: chassiConfigurations },
];

export default {
  version: 'ford-brasil-current-2026-09-12-v2',
  capturedOn,
  brand: 'Ford',
  sources,
  attributes,
  models: [...modelsPartOne, ...modelsPartTwo],
  expected: {
    modelCount: 12,
    configurationCount: 44,
  },
  supersessions: [
    {
      configurationId: '08e08761-a2e7-5ae5-b2ad-387e93829fb7',
      target: {
        model: 'Ranger',
        name: 'Black 2.0L 4x2 AT Diesel',
        market: 'BR',
        modelYear: 2027,
      },
    },
    {
      configurationId: 'f94a2350-0a1a-5ad3-aef8-3c0c472c72a1',
      target: {
        model: 'Ranger',
        name: 'Limited 3.0 V6 Diesel 4WD AT',
        market: 'BR',
        modelYear: 2027,
      },
    },
  ],
};
