const illustrative = (
  brand,
  model,
  file,
  sourceUrl,
  sourcePageUrl,
  names,
  extra = {},
) => ({
  brand,
  model,
  file,
  sourceUrl,
  sourcePageUrl,
  ...(names === undefined ? {} : { names }),
  matchScope: 'ILLUSTRATIVE',
  matchNote: `Official current ${brand} ${model} image shared by the manufacturer across the selected configurations; it does not establish color or trim-specific appearance.`,
  ...extra,
});

const exact = (
  brand,
  model,
  name,
  file,
  sourceUrl,
  sourcePageUrl,
  extra = {},
) => ({
  brand,
  model,
  name,
  file,
  sourceUrl,
  sourcePageUrl,
  matchScope: 'EXACT_CONFIGURATION',
  matchNote: `Official current ${brand} image linked to the ${model} ${name} configuration by the manufacturer page.`,
  ...extra,
});

const masterCargo = [
  'Furgão L1H1',
  'Furgão L2H2',
  'Furgão L3H2',
  'Pro L1H1',
  'Pro L2H2',
  'Pro L3H2',
];
const dailyCargo = [
  'Furgão 30-160',
  'Furgão 45-160 Manual',
  'Furgão 45-180 Hi-Matic',
  'Furgão 55-180 Manual',
  'Furgão 55-180 Hi-Matic',
];
const dailyChassis = [
  'Chassi 30-160',
  'Chassi 35-160',
  'Chassi 35-180',
  'Chassi 45-160',
  'Chassi 45-180',
  'Chassi 55-180',
  'Chassi 60-180 Motorhome',
  'Chassi 65-180',
  'Chassi 70-180 Motorhome',
];
const eDailyCargo = ['Furgão 3,5 t', 'Furgão 4,2 t', 'Furgão 7,2 t'];
const eDailyChassis = [
  'Chassi-cabine 3,5 t',
  'Chassi-cabine 4,2 t',
  'Chassi-cabine 7,2 t',
];
const sprinterChassis = [
  'Chassi 317 Street 3,5 t Longo',
  'Chassi 317 Street 3,5 t Extra-longo',
  'Chassi 417 4,1 t Longo',
  'Chassi 517 5,0 t Longo',
  'Chassi 517 5,0 t Extra-longo',
];
const sprinterCargo = [
  'Furgão 317 Street 3,5 t Longo Teto Alto',
  'Furgão 317 Street 3,5 t Longo Teto Baixo',
  'Furgão 317 Street 3,5 t Extra-longo Teto Alto',
  'Furgão 417 4,1 t Longo Teto Alto',
  'Furgão 417 4,1 t Longo Teto Baixo',
  'Furgão 417 4,1 t Extra-longo Teto Alto',
  'Furgão 517 5,0 t Extra-longo Teto Alto',
  'Furgão 517 5,0 t Extra-longo Prolongado Teto Alto',
];
const sprinterPassenger = [
  'Van 417 4,1 t Longo Teto Alto 15+1 Reclinável',
  'Van 417 4,1 t Longo Teto Alto 15+1 Fixo',
  'Van 417 4,1 t Longo Teto Alto 9+1',
  'Van 417 4,1 t Longo Teto Baixo 15+1',
  'Van 517 5,0 t Extra-longo 17+1',
  'Van 517 5,0 t Extra-longo Prolongado 19+1',
  'Van 517 5,0 t Extra-longo Prolongado 20+1',
];

export default [
  illustrative(
    'Chevrolet',
    'S10',
    'chevrolet-s10.jpg',
    'https://www.chevrolet.com.br/content/dam/chevrolet/south-america/brazil/portuguese/index/visid/pickups-and-trucks/2026-s10/mov/refresh-2027/versiones/1/high-country-card-versoes-2027.jpeg?imwidth=1200',
    'https://www.chevrolet.com.br/picapes/s10',
  ),
  illustrative(
    'Chevrolet',
    'Montana',
    'chevrolet-montana.jpg',
    'https://www.chevrolet.com.br/content/dam/chevrolet/south-america/brazil/portuguese/index/visid/pickups-and-trucks/2026-montana/refresh-2027/gallery/v2-img-aberta-01.jpeg?imwidth=1200',
    'https://www.chevrolet.com.br/picapes/chevrolet-montana',
  ),
  illustrative(
    'Chevrolet',
    'Silverado',
    'chevrolet-silverado.jpg',
    'https://www.chevrolet.com.br/content/dam/chevrolet/south-america/brazil/portuguese/index/visid/pickups-and-trucks/2026-silverado/mov/mh/chevrolet-picapes-silverado-2025-mh-desk.jpg?imwidth=1200',
    'https://www.chevrolet.com.br/picapes/nova-silverado',
  ),
  illustrative(
    'Toyota',
    'Hilux',
    'toyota-hilux.jpg',
    'https://media.toyota.com.br/ab3d2b27-55a1-482c-9f38-0e1408deb498.jpeg',
    'https://www.toyota.com.br/modelos/hilux-cabine-dupla',
    undefined,
    { browserCaptured: true },
  ),
  illustrative(
    'Toyota',
    'Corolla Cross',
    'toyota-corolla-cross.jpg',
    'https://media.toyota.com.br/7bbdd3d4-a44e-4bfc-bb92-52cb1af4ef2a.jpeg',
    'https://www.toyota.com.br/modelos/corolla-cross',
    undefined,
    { browserCaptured: true },
  ),
  exact(
    'Toyota',
    'Hiace',
    'Minibus AT DX 15+1',
    'toyota-hiace-minibus.jpg',
    'https://media.toyota.com.br/fbbe2ea8-7ed8-4e4e-bd39-c7cd0cbc9426.jpeg',
    'https://www.toyota.com.br/modelos/hiace',
    { browserCaptured: true },
  ),
  exact(
    'Toyota',
    'Hiace',
    'Furgão AT DX',
    'toyota-hiace-furgao.jpg',
    'https://media.toyota.com.br//b8f79000-0be3-474d-aa7c-e9760f0f4c31.jpeg',
    'https://www.toyota.com.br/modelos/hiace-furgao',
    { browserCaptured: true },
  ),
  illustrative(
    'Mitsubishi',
    'Nova Triton',
    'mitsubishi-nova-triton.webp',
    'https://media.mitsubishimotors.com.br/uploads/originals/Triton_GL_MT_4x4_3_4_frente_le_azul_baikal_1a9633d8d7_ae564ef05f.webp',
    'https://www.mitsubishimotors.com.br/configurador/nova-triton',
  ),
  illustrative(
    'GWM',
    'Poer',
    'gwm-poer-p30.jpg',
    'https://www.gwmmotors.com.br/content/dam/gwm/pages/br/pt/media-center/modelos/poer-p30/poer-p30-novas/alta-lineup-2.jpeg',
    'https://www.gwmmotors.com.br/pt/modelos/poer-p30-exclusive',
  ),
  illustrative(
    'GWM',
    'Haval H6',
    'gwm-haval-h6.jpg',
    'https://www.gwmmotors.com.br/content/dam/gwm/pages/br/pt/media-center/modelos/gwm-haval-h6-flex/hev-one/1.jpg',
    'https://www.gwmmotors.com.br/pt/modelos/haval-h6',
  ),
  exact(
    'GWM',
    'Tank 300',
    'PHEV Flex',
    'gwm-tank-300.webp',
    'https://www.gwmmotors.com.br/content/dam/gwm/pages/br/pt/models/tank-300/gerais/banner-hero-tank-300.webp',
    'https://www.gwmmotors.com.br/pt/modelos/tank-300',
  ),
  exact(
    'GWM',
    'Tank 300',
    'TerraForce',
    'gwm-tank-300-terraforce.webp',
    'https://www.gwmmotors.com.br/content/dam/gwm/pages/br/pt/models/tank-300-terra-force/banner-lancamento-gwm-desk.webp',
    'https://www.gwmmotors.com.br/pt/modelos/tank-300-terraforce',
  ),
  illustrative(
    'JAC',
    'Hunter',
    'jac-hunter.webp',
    'https://www.jacmotors.com.br/wp-content/uploads/2025/12/Hunter-Desktop-Feita-Para-Desbravar-1.webp',
    'https://www.jacmotors.com.br/picapes/hunter/',
  ),
  illustrative(
    'JAC',
    'E-JV5.5',
    'jac-e-jv55.png',
    'https://www.jacmotors.com.br/wp-content/uploads/2026/01/vans-1-e1769627981730.png',
    'https://www.jacmotors.com.br/vans/e-jv55/',
  ),
  illustrative(
    'JAC',
    'E-JV7L',
    'jac-e-jv7l.png',
    'https://www.jacmotors.com.br/wp-content/uploads/2026/01/vans-3-e1769628785115.png',
    'https://www.jacmotors.com.br/vans/e-jv7l/',
  ),
  illustrative(
    'JAC',
    'E-JV12',
    'jac-e-jv12.png',
    'https://www.jacmotors.com.br/wp-content/uploads/2026/01/V12-e1769629330277.png',
    'https://www.jacmotors.com.br/vans/e-jv12/',
  ),
  illustrative(
    'JAC',
    'E-JV12 VIP',
    'jac-e-jv12-vip.png',
    'https://www.jacmotors.com.br/wp-content/uploads/2026/01/VIP-12-e1769630446543.png',
    'https://www.jacmotors.com.br/vans/e-jv12-vip/',
  ),
  illustrative(
    'JAC',
    'E-JV CC',
    'jac-e-jv-cc.png',
    'https://www.jacmotors.com.br/wp-content/uploads/2026/01/T1-e1769631211379.png',
    'https://www.jacmotors.com.br/vans/e-jvcc/',
  ),
  exact(
    'Nissan',
    'Frontier',
    'S MT 4x4',
    'nissan-frontier-s.jpg',
    'https://www.nissan-cdn.net/content/dam/Nissan/br/site/veiculos/frontier-my24/DDT/thumbnails/S%20MT%204X4.jpg',
    'https://www.nissan.com.br/veiculos/dst-home/frontier-my24.html',
  ),
  exact(
    'Nissan',
    'Frontier',
    'SE AT 4x4',
    'nissan-frontier-se.jpg',
    'https://www.nissan-cdn.net/content/dam/Nissan/br/site/veiculos/frontier-my24/DDT/thumbnails/SE%20AT%204X4.jpg',
    'https://www.nissan.com.br/veiculos/dst-home/frontier-my24.html',
  ),
  exact(
    'Nissan',
    'Frontier',
    'Attack AT 4x4',
    'nissan-frontier-attack.jpg',
    'https://www.nissan-cdn.net/content/dam/Nissan/br/site/veiculos/frontier-my24/DDT/thumbnails/ATTACK%20AT%204X4.jpg',
    'https://www.nissan.com.br/veiculos/dst-home/frontier-my24.html',
  ),
  exact(
    'Nissan',
    'Frontier',
    'XE AT 4x4',
    'nissan-frontier-xe.jpg',
    'https://www.nissan-cdn.net/content/dam/Nissan/br/site/veiculos/frontier-my24/DDT/thumbnails/XE%20AT%204X4.jpg',
    'https://www.nissan.com.br/veiculos/dst-home/frontier-my24.html',
  ),
  exact(
    'Nissan',
    'Frontier',
    'Platinum AT 4x4',
    'nissan-frontier-platinum.jpg',
    'https://www.nissan-cdn.net/content/dam/Nissan/br/site/veiculos/frontier-my24/DDT/thumbnails/PLATINUM%20AT%204X4.jpg',
    'https://www.nissan.com.br/veiculos/dst-home/frontier-my24.html',
  ),
  exact(
    'Nissan',
    'Frontier',
    'PRO-4X AT 4x4',
    'nissan-frontier-pro4x.jpg',
    'https://www.nissan-cdn.net/content/dam/Nissan/br/site/veiculos/frontier-my24/DDT/thumbnails/PRO-4X%20AT%204X4.jpg',
    'https://www.nissan.com.br/veiculos/dst-home/frontier-my24.html',
  ),
  illustrative(
    'Volkswagen',
    'Amarok',
    'volkswagen-amarok.jpg',
    'https://www.vw.com.br/idhub/content/dam/onehub_pkw/importers/br/literatura-de-bordo/manual-amarok/my26/Manual%20de%20instru%C3%A7%C3%B5es_Amarok_MY26_Brasil.pdf',
    'https://www.vw.com.br/pt/carros.html/__app/amarok.app',
    undefined,
    { renderPdfPage: 1 },
  ),
  illustrative(
    'RAM',
    'Dakota',
    'ram-dakota.webp',
    'https://www.ram.com.br/content/dam/ram/dakota/my25/00-dakota-open-graph-3.webp',
    'https://www.ram.com.br/picapes/dakota/monte.html',
  ),
  illustrative(
    'RAM',
    'Rampage',
    'ram-rampage.webp',
    'https://www.ram.com.br/content/dam/ram/open-graph/rampage-open-graph-3.webp',
    'https://www.ram.com.br/picapes/rampage.html',
  ),
  illustrative(
    'RAM',
    '1500',
    'ram-1500.webp',
    'https://www.ram.com.br/content/dam/ram/1500/1500-limited/1500-open-graph-3.webp',
    'https://www.ram.com.br/picapes/1500/monte.html',
  ),
  illustrative(
    'Fiat',
    'Toro',
    'fiat-toro.webp',
    'https://toro.fiat.com.br/content/dam/fiat/toro-prox/banner-fiat-toro-hibridos-leves-mhev-desk.webp',
    'https://toro.fiat.com.br/monte.html',
  ),
  illustrative(
    'Fiat',
    'Ducato',
    'fiat-ducato.jpg',
    'https://ducato.fiat.com.br/content/dam/fiat/open_graph_rebrand/open-graph-ducato.jpg',
    'https://ducato.fiat.com.br/monte.html',
  ),
  illustrative(
    'Renault',
    'Oroch',
    'renault-oroch.jpg',
    'https://cdn.group.renault.com/ren/br/renault-new-cars/product-plans/2026/oroch/M01-U79Ph2-MY26-SS-Iconic-34AvGGrisTaupeNakeaDiamBiTonStaticMaisonSanEsteban-Brazil1440.jpg.ximg.large.jpg/5648d141fc.jpg',
    'https://www.renault.com.br/veiculos-de-passeio/oroch.html',
  ),
  exact(
    'Renault',
    'Master',
    'Minibus Executive L3H2 16 lugares',
    'renault-master-minibus.jpg',
    'https://cdn.group.renault.com/ren/br/renault-new-cars/product-plans/2026/master/vitre-selo.jpg.ximg.xsmall.jpg/924eeac762.jpg',
    'https://www.renault.com.br/veiculos-utilitarios/master-minibus/versoes-e-precos.html',
  ),
  illustrative(
    'Renault',
    'Master',
    'renault-master-furgao.jpg',
    'https://cdn.group.renault.com/ren/br/renault-new-cars/product-plans/2026/master/FURGAO-selo.jpg.ximg.xsmall.jpg/d46fbe120c.jpg',
    'https://www.renault.com.br/veiculos-utilitarios/master-furgao/versoes-e-precos.html',
    masterCargo,
  ),
  exact(
    'Renault',
    'Master',
    'Chassi Cabine L2H1',
    'renault-master-chassi.jpg',
    'https://cdn.group.renault.com/ren/br/renault-new-cars/product-plans/2026/master/chassi-selo.jpg.ximg.xsmall.jpg/425b5fffd0.jpg',
    'https://www.renault.com.br/veiculos-utilitarios/master-chassi/versoes-e-precos.html',
  ),
  illustrative(
    'BYD',
    'Shark',
    'byd-shark.jpg',
    'https://www.byd.com/material/byd-site/br/product/shark/exterior/New_Shark_2.jpg',
    'https://www.byd.com/br/car/shark',
  ),
  illustrative(
    'BYD',
    'Sealion 7',
    'byd-sealion-7.jpg',
    'https://www.byd.com/material/byd-site/br/product/sealion/imagens/product/banner/banner-2-pc.jpg',
    'https://www.byd.com/br/car/sealion7',
  ),
  exact(
    'CAOA Chery',
    'Tiggo 7',
    'Novo Tiggo 7 Sport',
    'caoa-chery-tiggo-7-sport.webp',
    'https://cloudfront.alpes.one/public/6a8/70e/0fb/6a870e0fbb3b8120454247.webp',
    'https://caoachery.com.br/novos/tiggo-7-sport-2027',
  ),
  exact(
    'CAOA Chery',
    'Tiggo 7',
    'Novo Tiggo 7 Pro',
    'caoa-chery-tiggo-7-pro.webp',
    'https://cloudfront.alpes.one/public/6a8/768/cd2/6a8768cd23300152882564.webp',
    'https://caoachery.com.br/novos/tiggo-7-pro-2027',
  ),
  exact(
    'CAOA Chery',
    'Tiggo 7',
    'Tiggo 7 Pro Hybrid Max Drive',
    'caoa-chery-tiggo-7-hybrid.webp',
    'https://cloudfront.alpes.one/public/6a1/d9d/5f6/6a1d9d5f6f822773946778.webp',
    'https://caoachery.com.br/novos/tiggo-7-pro-hybrid-max-drive',
  ),
  exact(
    'CAOA Chery',
    'Tiggo 7',
    'Tiggo 7 Pro PHEV',
    'caoa-chery-tiggo-7-phev.webp',
    'https://cloudfront.alpes.one/public/6a4/586/cbe/6a4586cbe7294383585326.webp',
    'https://caoachery.com.br/novos/tiggo-7-pro-plug-in-hybrid',
  ),
  illustrative(
    'Jeep',
    'Compass',
    'jeep-compass.webp',
    'https://www.jeep.com.br/content/dam/jeep/open-graph/compass-open-graph-3.webp',
    'https://www.jeep.com.br/compass/monte.html?year=2026',
  ),
  illustrative(
    'Jeep',
    'Wrangler',
    'jeep-wrangler.webp',
    'https://www.jeep.com.br/content/dam/jeep/open-graph/wrangler-open-graph-3.webp',
    'https://www.jeep.com.br/wrangler/monte.html?year=2026',
  ),
  illustrative(
    'Volvo',
    'EX40',
    'volvo-ex40.jpg',
    'https://www.volvocars.com/images/cs/v3/assets/blt0feaa88e629251fc/bltb9ae24a2f20b9084/684c305166912651b0c49a66/my26_ex40_ext_side_left_16x9.jpg?branch=prod_alias&quality=85&format=jpg&h=1080&iar=0&w=1920',
    'https://www.volvocars.com/br/cars/ex40-electric/',
  ),
  illustrative(
    'Zeekr',
    '7X',
    'zeekr-7x.webp',
    'https://www.datocms-assets.com/146515/1752697733-mobile.png?auto=format',
    'https://www.zeekrlife.com/pt-br/posts/suv-zeekr-7x-chega-ao-mercado-de-eletricos-premium',
  ),
  exact(
    'Porsche',
    'Macan',
    'Macan 4',
    'porsche-macan-4.webp',
    'https://models.porsche.com/_next/image?url=https%3A%2F%2Fprs.porsche.com%2Fiod%2Fimage%2FBR%2FXABBB1%2F1%2FN4Igxg9gdgZglgcxALlAQynAtmgLnaAZxQG0BdAGnDSwFMAnNFUOAExRFoA9cBaAGwgB3XjHrQ%2B-WjFwgqEAA74izEADc09OBlnIQrWoQDWuRSAC%2B5qrShq44qHSi6W7PQHUAFnFwMIELABBfgVPJnklAihiVEsqfkRPfCgkVBA2DgARQIBNORBFZWjmOJAFcVYAVzAXdLcQAA1AgCFWgEZ8wqiY0EhYRFIQNuaAaXy2gHEADnGAOQBmcYAVACZ8lYAxDqoV9wBOfPmNgFVDgGU1qgAWAFEANnyrkYfrgBkXkABWK4AlfM%2BGgBhfJ3ACSiyodwAsvkAOx3QL5QJjKgTNoALXyoPcEJAACkbpcQK8JktMj9XvkAIqTfLHBqw-IANUBa0o4AglWc9AAnhxmn8qFgIAZ%2BDlaJoUCsAAwrO6WKwgQi0XDJBA9EAwCD0HC6MopfK4RjRBSaGy6I2VWiWIA%3FclientId%3Dicc&w=1920&q=100',
    'https://models.porsche.com/pt-BR/model-start/macan',
    { browserCaptured: true },
  ),
  exact(
    'Porsche',
    'Macan',
    'Macan 4S',
    'porsche-macan-4s.webp',
    'https://models.porsche.com/_next/image?url=https%3A%2F%2Fprs.porsche.com%2Fiod%2Fimage%2FBR%2FXABDC1%2F1%2FN4Igxg9gdgZglgcxALlAQynAtmgLnaAZxQG0BdAGnDSwFMAnNFUOAExRFoA9cBaAGwgB3XjHrQ%2B-WjFwgqEAA74izEADc09OBlnIQrWoQDWuRSAC%2B5qrShq44qHSi6W7PQHUAFnFwMIELABBfgVPJnklAihiVEsqfkRPfCgkVBA2DgARQIBNORBFZWjmOJAFcVYAVzAXdLcQAA1AgCFMgGEARnzCqJjQSFhEUhAO5oBpfI6AcQAOSYA5AGZJgBUAJny1toB2TYAxLqo19wBOfMWAZQ2qABYAUQA2fJuxp9uAGTeQAFYGtvyHgBJZZUGbvAAS%2BRmKxBIBOgUhVBOADV3vlAhMqG0pt98nsVocQFMOgAtfKA9ywgBSd2uIDGzRu%2BXeUxWmQASmiqPMmVQAIprKn5PlU3kgACqAAVCeKGrsqMi2htKOAIJVnPQAJ4cZrs-JYCAGfg5WiaFBrAAMa22lisIEItFwyQQfRAMAg9BwujKKXyuEY0QUmhsun9lVoliAA%3FclientId%3Dicc&w=1920&q=100',
    'https://models.porsche.com/pt-BR/model-start/macan',
    { browserCaptured: true },
  ),
  exact(
    'Porsche',
    'Macan',
    'Macan GTS',
    'porsche-macan-gts.webp',
    'https://models.porsche.com/_next/image?url=https%3A%2F%2Fprs.porsche.com%2Fiod%2Fimage%2FBR%2FXABDE1%2F1%2FN4Igxg9gdgZglgcxALlAQynAtmgLnaAZxQG0BdAGnDSwFMAnNFUOAExRFoA9cBaAGwgB3XjHrQ%2B-WjFwgqEAA74izEADc09OBlnIQrWoQDWuRSAC%2B5qrShq44qHSi6W7PQHUAFnFwMIELABBfgVPJnklAihiVEsqfkRPfCgkVBA2DgARQIBNORBFZWjmOJAFcVYAVzAXdLcQAA1AgCFMgFEARnzCqJjQSFhEUhAABgAZfI6AcQAOSYA5AGZJgBUAJkmALTb8tYAxLqo19wBOXc2ANXzFgGUNqgAWNoA2fIeAaVfHsa%2BQAFYZgAJfJ-ACywKofwaAGF8s8AJLLKgzFZIkAnQIQ9EXCZUPYrQ4gKYdTb5eHuNEAKTa9xAYymK0yACVcSAAIodSn5G7zfIAVQaAHZ8hdoRtKOAIJVnPQAJ4cZpM-JYCAGfg5WiaFBrEZrQWWKwgQi0XDJBB9EAwCD0HC6MopfK4RjRBSaGy6J2VWiWIA%3FclientId%3Dicc&w=1920&q=100',
    'https://models.porsche.com/pt-BR/model-start/macan',
    { browserCaptured: true },
  ),
  exact(
    'Porsche',
    'Macan',
    'Macan Turbo',
    'porsche-macan-turbo.webp',
    'https://models.porsche.com/_next/image?url=https%3A%2F%2Fprs.porsche.com%2Fiod%2Fimage%2FBR%2FXABFD1%2F1%2FN4Igxg9gdgZglgcxALlAQynAtmgLnaAZxQG0BdAGnDSwFMAnNFUOAExRFoA9cBaAGwgB3XjHrQ%2B-WjFwgqEAA74izEADc09OBlnIQrWoQDWuRSAC%2B5qrShq44qHSi6W7PQHUAFnFwMIELABBfgVPJnklAihiVEsqfkRPfCgkVBA2DgARQIBNORBFZWjmOJAFcVYAVzAXdLcQAA1AgCEAMUyARnzCqJjQSFhEUhAOgHEADnyOgDkANSmAFQAmfKXWrqol9wBOfIBmAGUAdn2ck6oAFgBRADZ8i4BpO6oAVgaAYXybgEk9-PGADIACX%2BCz%2BVG2gRBEIAUpl8oEAKobEDvI4A-KtBYo0YdABa%2BVG5xA33c4JAMKuKyoANGC0yACUMVQAIodGH5RENYmzQL5WbvFaUcAQSrOegATw4zQZ%2BSwEAM-BytE0KCWAAYlkdLFYQIRaLhkgg%2BiAYBB6DhdGUUvlcIxogpNDZdHbKrRLEA%3FclientId%3Dicc&w=1920&q=100',
    'https://models.porsche.com/pt-BR/model-start/macan',
    { browserCaptured: true },
  ),
  illustrative(
    'BMW',
    'M2',
    'bmw-m2.jpg',
    'https://mediapool.bmwgroup.com/cache/P9/202406/P90553471/P90553471-der-neue-bmw-m2-06-2024-600px.jpg',
    'https://www.bmw.com.br/pt/all-models/m-series/bmw-2-series-m-models/m2-coupe-2024-g87.html',
  ),
  illustrative(
    'BMW',
    'M4',
    'bmw-m4.jpg',
    'https://mediapool.bmwgroup.com/cache/P9/202401/P90536868/P90536868-the-new-bmw-m4-coup-the-new-bmw-m4-convertible-600px.jpg',
    'https://www.bmw.com.br/pt/all-models/m-series/bmw-4-series-m-models/bmw-m4-coupe.html',
  ),
  illustrative(
    'Iveco',
    'Daily',
    'iveco-daily-furgao.png',
    'https://www.iveco.com/brasil/-/media/IVECOdotcom/Brasil/Daily/Van/furgao_hero.png?h=1024&iar=0&w=1536&rev=-1',
    'https://www.iveco.com/brasil/Daily/Daily-Furgao',
    dailyCargo,
  ),
  illustrative(
    'Iveco',
    'Daily',
    'iveco-daily-chassi.jpg',
    'https://www.iveco.com/brasil/-/media/IVECOdotcom/Brasil/Hero/Daily/Cab/DailyCABv4.jpg?h=1080&iar=0&w=1920&rev=a5de8347666c46128d6fd8f4c603f553',
    'https://www.iveco.com/brasil/Daily/Daily-Cabine-chassi',
    dailyChassis,
  ),
  illustrative(
    'Iveco',
    'eDaily',
    'iveco-edaily-furgao.png',
    'https://www.iveco.com/brasil/-/media/IVECOdotcom/Brasil/eDaily/furgao/IVECO-eDaily-furgao-702x472.png?h=473&iar=0&w=702&rev=077d38abf2de43dbbe6311b147b5c637',
    'https://www.iveco.com/brasil/eDaily',
    eDailyCargo,
  ),
  illustrative(
    'Iveco',
    'eDaily',
    'iveco-edaily-chassi.png',
    'https://www.iveco.com/brasil/-/media/IVECOdotcom/Brasil/eDaily/Cab/IVECO-eDaily-graneleiro-702x425.png?h=426&iar=0&w=702&rev=bf5f500114ff4d8cb38029a9df90c0f0',
    'https://www.iveco.com/brasil/eDaily',
    eDailyChassis,
  ),
  illustrative(
    'Mercedes-Benz',
    'Sprinter',
    'mercedes-sprinter-chassi.jpg',
    'https://www2.mercedes-benz.com.br/content/dam/brazil/vans/homepage/mercedes-benz-vans-sprinter-truck-campaigns-component9x16.jpg/1778763903748.jpg?im=Crop%2Crect%3D%2847%2C0%2C1205%2C1205%29%3BResize%3D%28800%2C800%29',
    'https://www2.mercedes-benz.com.br/vans/pt_br/sprinter',
    sprinterChassis,
  ),
  illustrative(
    'Mercedes-Benz',
    'Sprinter',
    'mercedes-sprinter-furgao.jpg',
    'https://www2.mercedes-benz.com.br/content/dam/brazil/vans/homepage/mercedes-benz-vans-sprinter-panelvan-campaigns-component9x16.jpg/1778763903748.jpg?im=Crop%2Crect%3D%280%2C300%2C1200%2C1200%29%3BResize%3D%28800%2C800%29',
    'https://www2.mercedes-benz.com.br/vans/pt_br/sprinter',
    sprinterCargo,
  ),
  illustrative(
    'Mercedes-Benz',
    'Sprinter',
    'mercedes-sprinter-van.jpg',
    'https://www2.mercedes-benz.com.br/content/dam/brazil/vans/homepage/mercedes-benz-vans-sprinter-passenger-van-campaigns-component1x1.jpg/1778763903748.jpg?im=Crop%2Crect%3D%2855%2C0%2C1390%2C1390%29%3BResize%3D%28800%2C800%29',
    'https://www2.mercedes-benz.com.br/vans/pt_br/sprinter',
    sprinterPassenger,
  ),
  illustrative(
    'Mercedes-Benz',
    'eSprinter',
    'mercedes-esprinter.jpg',
    'https://www2.mercedes-benz.com.br/content/dam/brazil/vans/esprinter/mercedes-benz-vans-esprinter-electric-panel-van-teaser-2000x1333.jpg/1780946409619.jpg?im=Crop%2Crect%3D%28262%2C8%2C1730%2C1298%29%3BResize%3D%28600%2C450%29',
    'https://www2.mercedes-benz.com.br/vans/pt_br/esprinter',
  ),
];
