-- Linguistic aliases for the attribute definitions proposed by the catalog gap audit
-- 2026-09-21T12-00-00Z (accepted definitions in tools/catalog/*/gap-audit-*.mjs).
-- The join yields nothing until the dataset is imported; apps/ai/data re-runs this
-- file after seeding, exactly like V4 and V18.
INSERT INTO catalog.attribute_alias(id,attribute_id,term,language)
SELECT md5(a.id::text || ':' || terms.term)::uuid,a.id,terms.term,'pt-BR'
FROM catalog.attribute_definition a JOIN (VALUES
 ('ground_clearance','vão livre do solo'),('ground_clearance','vão-livre do solo'),('ground_clearance','vão livre mínimo do solo'),
 ('ground_clearance','distância do solo'),('ground_clearance','altura mínima do solo'),('ground_clearance','altura livre em relação ao solo'),
 ('ground_clearance','mínima altura livre do solo'),('ground_clearance','ground clearance'),('steering_type','tipo de direção'),
 ('steering_type','tipo de direcao'),('steering_type','assistência de direção'),('steering_type','assistencia de direcao'),
 ('steering_type','direção assistida'),('steering_type','steering type'),('steering_type','steering assist type'),
 ('departure_angle','departure angle'),('front_brakes','freio dianteiro'),('front_brakes','front brakes'),
 ('rear_brakes','freio traseiro'),('rear_brakes','rear brakes'),('approach_angle','ângulo de entrada'),
 ('approach_angle','approach angle'),('vehicle_warranty','garantia de fábrica'),('vehicle_warranty','garantia do veículo'),
 ('vehicle_warranty','factory warranty'),('vehicle_warranty','warranty'),('brake_system','freios'),
 ('brake_system','sistema de freio'),('brake_system','freio de serviço'),('brake_system','brakes'),
 ('track_front','bitola dianteira'),('track_front','bitola eixo dianteiro'),('track_front','largura entre rodas dianteiras'),
 ('track_front','largura do eixo dianteiro'),('track_front','front track'),('airbag_count','airbags'),
 ('airbag_count','air bags'),('airbag_count','quantidade de airbags'),('airbag_count','número de airbags'),
 ('cylinder_count','cilindros'),('cylinder_count','número de cilindros'),('cylinder_count','cylinders'),
 ('track_rear','bitola traseira'),('track_rear','bitola eixo traseiro'),('track_rear','largura entre rodas traseiras'),
 ('track_rear','largura do eixo traseiro'),('track_rear','rear track'),('dc_charge_time_10_80','recarga DC 10-80%'),
 ('dc_charge_time_10_80','tempo de recarga rápida 10-80%'),('dc_charge_time_10_80','carregamento DC 10%-80%'),('dc_charge_time_10_80','DC charging time 10-80%'),
 ('final_drive_ratio','relação final'),('final_drive_ratio','relação do eixo traseiro'),('final_drive_ratio','relação de diferencial'),
 ('final_drive_ratio','axle ratio'),('battery_chemistry','química da bateria'),('battery_chemistry','tipo de bateria'),
 ('battery_chemistry','tecnologia da bateria'),('battery_chemistry','battery chemistry'),('multimedia_screen_size','tamanho da tela multimídia'),
 ('multimedia_screen_size','tamanho da central multimídia'),('multimedia_screen_size','tela central multifuncional'),('multimedia_screen_size','polegadas da tela multimídia'),
 ('turning_diameter_unspecified','diâmetro de giro'),('turning_diameter_unspecified','diâmetro mínimo de curva'),('turning_diameter_unspecified','círculo de giro'),
 ('turning_diameter_unspecified','turning circle'),('turning_diameter_unspecified','turning diameter'),('fuel_consumption_highway','consumo rodoviário'),
 ('fuel_consumption_highway','consumo na estrada'),('fuel_consumption_highway','consumo estrada'),('fuel_consumption_highway','highway fuel economy'),
 ('fuel_consumption_city','consumo urbano'),('fuel_consumption_city','consumo na cidade'),('fuel_consumption_city','consumo cidade'),
 ('fuel_consumption_city','city fuel economy'),('ac_charge_time','tempo de recarga CA'),('ac_charge_time','tempo de recarga AC'),
 ('ac_charge_time','carregamento AC'),('ac_charge_time','carregamento CA'),('ac_charge_time','carregador AC wallbox'),
 ('ac_charge_time','tempo de carga wallbox'),('ac_charge_time','AC charging time'),('compression_ratio','taxa de compressão'),
 ('compression_ratio','relação de compressão'),('compression_ratio','compression ratio'),('gross_axle_weight_rear','peso máximo admissível no eixo traseiro'),
 ('gross_axle_weight_rear','peso máximo permitido no eixo traseiro'),('gross_axle_weight_rear','carga máxima admissível no eixo traseiro'),('gross_axle_weight_rear','carga admissível sobre o eixo traseiro'),
 ('gross_axle_weight_rear','capacidade máxima de carga no eixo traseiro'),('gross_axle_weight_rear','PBT eixo traseiro'),('gross_axle_weight_rear','capacidade do eixo traseiro'),
 ('gross_axle_weight_rear','rear GAWR'),('low_voltage_battery','bateria 12V'),('low_voltage_battery','bateria de baixa tensão'),
 ('low_voltage_battery','bateria de partida'),('low_voltage_battery','bateria auxiliar'),('low_voltage_battery','capacidade da bateria (Ah)'),
 ('low_voltage_battery','starter battery'),('battery_capacity_unspecified','capacidade da bateria (kWh)'),('battery_capacity_unspecified','bateria (kWh)'),
 ('battery_capacity_unspecified','capacidade de energia da bateria'),('battery_capacity_unspecified','capacidade da bateria de tração'),('battery_capacity_unspecified','bateria de tração kWh'),
 ('battery_capacity_unspecified','traction battery capacity'),('gross_axle_weight_front','carga máxima admissível no eixo dianteiro'),('gross_axle_weight_front','PBT eixo dianteiro'),
 ('gross_axle_weight_front','capacidade de carga homologada eixo dianteiro'),('gross_axle_weight_front','front GAWR'),('instrument_cluster_size','tela do painel de instrumentos'),
 ('instrument_cluster_size','tamanho do quadro de instrumentos'),('instrument_cluster_size','instrument cluster display size'),('spare_tire','pneu reserva'),
 ('spare_tire','pneu reserva de uso temporário'),('spare_tire','pneu do estepe'),('spare_tire','solução em caso de furo de pneu'),
 ('spare_tire','spare tire'),('spare_tire','spare wheel'),('emission_standard','norma de emissões'),
 ('emission_standard','norma de emissão'),('emission_standard','nível de emissão'),('emission_standard','classificação ambiental'),
 ('emission_standard','emissões'),('emission_standard','emission standard'),('engine_oil_capacity','capacidade de óleo do motor'),
 ('engine_oil_capacity','volume de óleo do motor'),('engine_oil_capacity','volume de óleo com filtro'),('engine_oil_capacity','quantidade de óleo do motor'),
 ('engine_oil_capacity','engine oil capacity'),('cargo_width_between_wheel_arches','largura entre caixas de roda'),('cargo_width_between_wheel_arches','distância entre caixas de roda'),
 ('cargo_width_between_wheel_arches','largura entre arcos das rodas'),('cargo_width_between_wheel_arches','largura da caçamba entre arcos das rodas'),('cargo_width_between_wheel_arches','zona de carga - largura entre rodas'),
 ('cargo_width_between_wheel_arches','largura interna entre caixa de rodas'),('cargo_width_between_wheel_arches','width between wheel arches'),('fuel_injection_type','injeção eletrônica'),
 ('fuel_injection_type','injeção de combustível'),('fuel_injection_type','tipo de injeção'),('fuel_injection_type','sistema de injeção'),
 ('fuel_injection_type','fuel injection'),('fuel_injection_type','fuel injection type'),('gear_ratios','relações de transmissão'),
 ('gear_ratios','relações das marchas'),('gear_ratios','relação de marchas'),('gear_ratios','gear ratios'),
 ('gradeability','capacidade de rampa'),('gradeability','inclinação máxima em subida'),('gradeability','gradeability'),
 ('traction_battery_warranty','garantia da bateria de tração'),('traction_battery_warranty','garantia da bateria de alta tensão'),('traction_battery_warranty','garantia da bateria de alta voltagem'),
 ('traction_battery_warranty','high-voltage battery warranty'),('traction_battery_warranty','traction battery warranty'),('valve_count','número de válvulas'),
 ('valve_count','nº de válvulas'),('valve_count','válvulas'),('valve_count','quantidade de válvulas'),
 ('valve_count','valve count'),('alternator_output','capacidade do alternador'),('alternator_output','alternador (A)'),
 ('alternator_output','alternador (V / A)'),('alternator_output','alternator output'),('alternator_output','alternator rating'),
 ('breakover_angle','ângulo de rampa'),('breakover_angle','ângulo ventral'),('breakover_angle','breakover angle'),
 ('rear_differential_lock','diferencial traseiro blocante'),('rear_differential_lock','diferencial traseiro blocante eletrônico'),('rear_differential_lock','bloqueio do diferencial traseiro'),
 ('rear_differential_lock','rear locker'),('rear_differential_lock','rear diff lock'),('rear_differential_lock','rear locking differential'),
 ('rear_wheel_arrangement','rodado'),('rear_wheel_arrangement','tipo de rodado'),('rear_wheel_arrangement','tipo rodado'),
 ('rear_wheel_arrangement','rear wheel configuration'),('rear_wheel_arrangement','rear wheel arrangement'),('stationary_noise_level','ruído estático'),
 ('stationary_noise_level','nível de ruído (veículo parado)'),('stationary_noise_level','nível de ruído (condição estática)'),('stationary_noise_level','nível de ruído na condição estática'),
 ('stationary_noise_level','nível de ruído para fiscalização'),('stationary_noise_level','nível sonoro máximo com veículo parado'),('stationary_noise_level','limite de ruído na condição parado'),
 ('stationary_noise_level','stationary noise level'),('turning_radius_unspecified','raio de giro'),('turning_radius_unspecified','raio mínimo de giro'),
 ('turning_radius_unspecified','turning radius'),('battery_gross_capacity','capacidade bruta'),('battery_gross_capacity','capacidade bruta da bateria'),
 ('battery_gross_capacity','energia instalada'),('battery_gross_capacity','capacidade total da bateria'),('battery_gross_capacity','capacidade total de energia da bateria'),
 ('battery_gross_capacity','gross battery capacity'),('battery_manufacturer','fabricante da bateria'),('battery_manufacturer','battery supplier'),
 ('battery_manufacturer','fornecedor da bateria'),('body_completion_stage','veículo inacabado'),('body_completion_stage','veículo incompleto'),
 ('body_completion_stage','acabado/inacabado'),('body_completion_stage','incomplete vehicle'),('charging_connectors','conector de recarga'),
 ('charging_connectors','plugue de carregamento'),('charging_connectors','interface de carregamento'),('charging_connectors','charging connector'),
 ('charging_connectors','charging inlet'),('charging_connectors','charging port'),('coolant_capacity','líquido de arrefecimento'),
 ('coolant_capacity','coolant capacity'),('curb_weight_front_axle','PVOM eixo dianteiro'),('curb_weight_front_axle','PVOM - eixo dianteiro'),
 ('curb_weight_front_axle','peso em ordem de marcha no eixo dianteiro'),('curb_weight_front_axle','front axle curb weight'),('curb_weight_rear_axle','PVOM - eixo traseiro'),
 ('curb_weight_rear_axle','PVOM eixo traseiro'),('curb_weight_rear_axle','peso em ordem de marcha no eixo traseiro'),('curb_weight_rear_axle','rear axle curb weight'),
 ('emission_aftertreatment','pós-tratamento'),('emission_aftertreatment','pós-tratamento de emissões'),('emission_aftertreatment','after-treatment'),
 ('emission_aftertreatment','aftertreatment'),('emission_aftertreatment','dispositivos antipoluição'),('emission_aftertreatment','tecnologia de pós-tratamento'),
 ('energy_consumption_pbev','consumo energético (MJ/km)'),('energy_consumption_pbev','energia (MJ/km)'),('energy_consumption_pbev','consumo energético PBEV'),
 ('load_floor_height_unladen','altura do piso de carga vazio'),('load_floor_height_unladen','altura do piso de carga descarregado'),('load_floor_height_unladen','altura de carga descarregado'),
 ('load_floor_height_unladen','altura de carga (descarregado)'),('load_floor_height_unladen','load floor height unladen'),('rear_axle_oil_capacity','óleo do diferencial traseiro'),
 ('rear_axle_oil_capacity','eixo traseiro - volume de óleo'),('rear_axle_oil_capacity','eixo traseiro diferencial'),('rear_axle_oil_capacity','rear axle oil'),
 ('speaker_count','alto-falantes'),('speaker_count','speakers'),('transmission_oil_capacity','óleo do câmbio'),
 ('transmission_oil_capacity','transmissão - volume de óleo'),('transmission_oil_capacity','caixa de câmbio (volume de abastecimento)'),('transmission_oil_capacity','volume de óleo da transmissão'),
 ('transmission_oil_capacity','transmission oil capacity'),('width_with_folded_mirrors','largura com retrovisores rebatidos'),('width_with_folded_mirrors','largura com espelhos recolhidos'),
 ('width_with_folded_mirrors','largura com espelho dobrado'),('width_with_folded_mirrors','largura com espelhos dobrados'),('width_with_folded_mirrors','largura (espelhos dobrados)'),
 ('width_with_folded_mirrors','width with folded mirrors'),('battery_cooling','bateria alta voltagem - refrigeração'),('battery_cooling','tipo de refrigeração da bateria'),
 ('battery_cooling','refrigeração da bateria'),('battery_cooling','arrefecimento da bateria'),('battery_cooling','battery cooling'),
 ('traction_battery_nominal_voltage','tensão nominal da bateria'),('traction_battery_nominal_voltage','tensão nominal da bateria de tração'),('traction_battery_nominal_voltage','voltagem da bateria de alta tensão'),
 ('traction_battery_nominal_voltage','traction battery nominal voltage'),('bed_side_storage_volume_each','compartimento lateral da caçamba'),('bed_side_storage_volume_each','bed side storage'),
 ('bed_side_storage_volume_each','bed side storage box'),('bore_stroke','diâmetro e curso'),('bore_stroke','diâmetro do cilindro e curso'),
 ('bore_stroke','bore x stroke'),('clutch_diameter','diâmetro do disco de embreagem'),('clutch_diameter','clutch diameter'),
 ('connected_services','serviços conectados'),('connected_services','serviços conectados do veículo'),('connected_services','connected services'),
 ('crash_test_rating','estrelas NCAP'),('crash_test_rating','Latin NCAP'),('crash_test_rating','Euro NCAP'),
 ('crash_test_rating','ANCAP'),('crash_test_rating','crash test'),('door_count','portas'),
 ('door_count','número de portas'),('door_count','door count'),('driver_license_category','CNH'),
 ('driver_license_category','habilitação'),('electric_motor_power_max','potência do motor elétrico'),('electric_motor_power_max','potência máxima do motor elétrico'),
 ('electric_motor_power_max','potência elétrica máxima'),('electric_motor_power_max','electric motor power'),('electric_motor_power_max','electric motor peak power'),
 ('electrical_architecture_voltage','arquitetura elétrica'),('electrical_architecture_voltage','sistema de alta voltagem'),('electrical_architecture_voltage','sistema de alta tensão'),
 ('electrical_architecture_voltage','sistema elétrico de 48 V'),('electrical_architecture_voltage','tensão do sistema'),('electrical_architecture_voltage','tensão do sistema híbrido'),
 ('electrical_architecture_voltage','voltage architecture'),('electrical_architecture_voltage','high-voltage architecture'),('electrical_architecture_voltage','system voltage'),
 ('heated_front_seats','bancos dianteiros com aquecimento'),('heated_front_seats','aquecimento do banco dianteiro'),('heated_front_seats','aquecimento do banco do motorista/passageiro dianteiro'),
 ('heated_front_seats','heated front seats'),('interior_colors','cor interna'),('interior_colors','cores internas'),
 ('interior_colors','cores interiores'),('interior_colors','opções de interior'),('interior_colors','cor do interior'),
 ('interior_colors','interior colors'),('load_floor_height_laden','altura de carga carregado'),('load_floor_height_laden','altura de carga (carregado)'),
 ('load_floor_height_laden','altura do piso de carga carregado'),('load_floor_height_laden','load floor height laden'),('low_range_ratio','relação de reduzida'),
 ('low_range_ratio','relação da reduzida'),('low_range_ratio','redução da caixa de transferência'),('low_range_ratio','relação de redução 4L'),
 ('low_range_ratio','low range ratio'),('acceleration_80_120','retomada 80-120'),('acceleration_80_120','retomada de velocidade 80-120 km/h'),
 ('acceleration_80_120','aceleração 80-120 km/h'),('acceleration_80_120','passing 80-120'),('parking_brake','freio de mão'),
 ('parking_brake','freio de estacionamento'),('parking_brake','parking brake'),('parking_brake','handbrake'),
 ('regen_braking_levels','níveis de regeneração de energia'),('regen_braking_levels','níveis do freio regenerativo'),('regen_braking_levels','níveis de regeneração'),
 ('regen_braking_levels','regen levels'),('roof_load_max','carga no teto'),('roof_load_max','capacidade das barras de teto'),
 ('roof_load_max','roof load'),('ventilated_front_seats','bancos ventilados'),('ventilated_front_seats','ventilação dos bancos'),
 ('ventilated_front_seats','refrigeração dos bancos'),('ventilated_front_seats','bancos refrigerados'),('ventilated_front_seats','ventilated seats'),
 ('battery_pack_weight','peso da bateria'),('battery_pack_weight','peso do pack'),('battery_pack_weight','battery weight'),
 ('cab_position','cabine semiavançada'),('cab_position','cabine avançada'),('cab_position','cabine convencional'),
 ('cab_position','posição da cabine'),('cab_position','cab position'),('cab_position','semi-forward control'),
 ('cab_position','forward control'),('cab_position','cab-over'),('cargo_floor_area','área de carga'),
 ('cargo_floor_area','superfície da caçamba'),('cargo_floor_area','cargo floor area'),('chassis_frame_height','altura chassi ao solo'),
 ('chassis_frame_height','altura máxima chassi ao solo'),('chassis_frame_height','altura do quadro do chassi ao solo'),('chassis_frame_height','altura das longarinas ao solo'),
 ('chassis_frame_height','frame height above ground'),('co2_emissions_fossil','CO2 fóssil'),('co2_emissions_fossil','CO2 fóssil não renovável'),
 ('co2_emissions_fossil','fossil CO2'),('cruise_control','piloto automático'),('cruise_control','controle de cruzeiro'),
 ('cruise_control','controle de velocidade de cruzeiro'),('cruise_control','cruise control'),('electric_energy_consumption_unspecified','consumo de energia elétrica'),
 ('electric_energy_consumption_unspecified','consumo elétrico'),('electric_energy_consumption_unspecified','kWh/100 km'),('electric_motor_count','número de motores elétricos'),
 ('electric_motor_count','quantidade de motores elétricos'),('electric_motor_count','electric motor count'),('electric_motor_position','posição do motor elétrico'),
 ('electric_motor_position','motor elétrico - posição'),('electric_motor_position','hybrid motor position'),('electric_motor_rated_power','potência nominal do motor elétrico'),
 ('electric_motor_rated_power','potência contínua do motor elétrico'),('electric_motor_rated_power','potência nominal/máxima'),('electric_motor_rated_power','electric motor rated power'),
 ('electric_motor_rated_power','continuous motor power'),('electric_motor_rated_torque','torque nominal do motor elétrico'),('electric_motor_rated_torque','torque nominal/máximo'),
 ('electric_motor_rated_torque','torque contínuo do motor elétrico'),('electric_motor_rated_torque','rated motor torque'),('energy_equivalent_economy_urban','km/le urbano'),
 ('energy_equivalent_economy_urban','km/e urbano'),('energy_equivalent_economy_urban','consumo urbano elétrico'),('energy_equivalent_economy_urban','autonomia urbana km/le'),
 ('energy_equivalent_economy_urban','consumo com gasolina urbano elétrico'),('engine_position','posição do motor'),('engine_position','posição (motor)'),
 ('engine_position','engine position'),('engine_position','engine layout'),('front_axle_to_body_front','eixo dianteiro até a carroceria'),
 ('front_axle_to_body_front','front axle to body'),('gross_vehicle_weight_technical','PBT técnico'),('gross_vehicle_weight_technical','technical GVW'),
 ('ground_clearance_front_axle','vão livre dianteiro'),('ground_clearance_front_axle','altura do solo dianteira'),('ground_clearance_front_axle','front ground clearance'),
 ('ground_clearance_rear_axle','vão livre traseiro'),('ground_clearance_rear_axle','altura do solo traseira'),('ground_clearance_rear_axle','rear ground clearance'),
 ('head_up_display','head-up display'),('head_up_display','HUD'),('head_up_display','projeção no para-brisa'),
 ('head_up_display','display de projeção'),('headroom_front','espaço para a cabeça dianteiro'),('headroom_front','altura nos assentos anteriores'),
 ('headroom_front','altura nos assentos dianteiros'),('headroom_front','H61-1'),('headroom_front','front headroom'),
 ('headroom_rear','espaço para a cabeça traseiro'),('headroom_rear','espaço para a cabeça atrás'),('headroom_rear','altura nos assentos posteriores'),
 ('headroom_rear','altura nos assentos traseiros'),('headroom_rear','H61-2'),('headroom_rear','rear headroom'),
 ('limited_slip_differential','diferencial de deslizamento limitado'),('limited_slip_differential','diferencial autobloqueante'),('limited_slip_differential','LSD'),
 ('limited_slip_differential','limited slip'),('limited_slip_differential','limited slip differential'),('limited_slip_differential','limited-slip differential'),
 ('acceleration_60_100','retomada 60-100'),('acceleration_60_100','retomada de velocidade 60-100 km/h'),('acceleration_60_100','aceleração 60-100 km/h'),
 ('portable_ac_charge_power','potência máxima de carregamento portátil AC'),('portable_ac_charge_power','potência do carregador portátil'),('portable_ac_charge_power','portable charger power'),
 ('powertrain_type','tipo de propulsão'),('powertrain_type','tipo de híbrido'),('powertrain_type','tipo de motorização'),
 ('powertrain_type','powertrain type'),('automatic_emergency_braking','AEB'),('automatic_emergency_braking','frenagem autônoma de emergência'),
 ('automatic_emergency_braking','frenagem automática de emergência'),('automatic_emergency_braking','frenagem autônoma'),('automatic_emergency_braking','autonomous emergency braking'),
 ('rear_axle_model','marca do eixo traseiro'),('rear_axle_model','rear axle model'),('shoulder_room_front','largura na altura dos ombros dianteira'),
 ('shoulder_room_front','shoulder room front'),('shoulder_room_rear','largura na altura dos ombros traseira'),('shoulder_room_rear','shoulder room rear'),
 ('smoke_opacity_index','índice de fumaça em aceleração'),('smoke_opacity_index','índice de fumaça'),('smoke_opacity_index','opacidade da fumaça'),
 ('startability','startability'),('startability','capacidade de partida em rampa'),('startability','partida em rampa (startability)'),
 ('startability','rampa máxima de partida'),('turning_diameter_curb_to_curb','diâmetro de giro entre guias'),('turning_diameter_curb_to_curb','diâmetro de giro (entre guias)'),
 ('turning_diameter_curb_to_curb','diâmetro de giro entre pneus'),('turning_diameter_curb_to_curb','curb to curb turning diameter'),('width_rear','largura veículo na parte traseira'),
 ('width_rear','largura do veículo na parte traseira'),('width_rear','rear width'),('acceleration_0_160','0 a 160'),
 ('acceleration_0_160','0-160 km/h'),('acceleration_0_200','0 a 200'),('acceleration_0_200','0-200 km/h'),
 ('acceleration_0_80','0 a 80'),('acceleration_0_80','0-80 km/h'),('adblue_range','autonomia do AdBlue'),
 ('adblue_range','autonomia do tanque de ureia'),('adblue_range','autonomia da ureia'),('air_suspension_height_mode_count','modos de altura'),
 ('air_suspension_height_mode_count','níveis de altura'),('air_suspension_height_mode_count','ride height modes'),('air_suspension_height_mode_count','air suspension height modes'),
 ('aspiration','aspiração'),('aspiration','sobrealimentação'),('aspiration','air induction'),
 ('aspiration','tipo de aspiração'),('battery_charge_capacity_ah','capacidade de corrente elétrica'),('battery_charge_capacity_ah','capacidade da bateria de tração (Ah)'),
 ('battery_charge_capacity_ah','capacidade da bateria de tração em Ah'),('battery_charge_capacity_ah','capacidade de carga da bateria (Ah)'),('battery_charge_capacity_ah','traction battery capacity Ah'),
 ('blind_spot_monitor','alerta de ponto cego'),('blind_spot_monitor','BSM'),('blind_spot_monitor','blind spot monitor'),
 ('blind_spot_monitor','monitoramento de ponto cego'),('body_construction','arquitetura da carroceria'),('body_construction','estrutura da carroceria'),
 ('body_construction','tipo de construção da carroceria'),('body_construction','body construction'),('body_construction','body architecture'),
 ('body_construction','ladder frame'),('body_construction','chassi tipo escada'),('body_construction','chassi escada'),
 ('braking_distance_100_0','frenagem 100-0 km/h'),('braking_distance_100_0','distância de frenagem 100-0'),('braking_distance_100_0','braking distance 100-0 km/h'),
 ('braking_distance_100_0','stopping distance 100-0 km/h'),('clutch','embreagem'),('clutch','clutch'),
 ('combustion_engine_power','potência do motor a combustão'),('combustion_engine_power','ICE power'),('crawl_ratio','crawl ratio'),
 ('crawl_ratio','relação de crawl'),('crawl_ratio','relação final de crawl'),('drag_coefficient','Cx'),
 ('drag_coefficient','Cd'),('drag_coefficient','coeficiente de arrasto'),('economy_rpm_range','faixa de rotação econômica'),
 ('economy_rpm_range','faixa verde de consumo'),('economy_rpm_range','faixa verde'),('economy_rpm_range','economy rpm range'),
 ('electric_motor_cooling','arrefecimento do motor elétrico'),('electric_motor_cooling','tipo de arrefecimento do motor elétrico'),('electric_motor_cooling','refrigeração do motor elétrico'),
 ('electric_motor_cooling','electric motor cooling'),('electric_motor_cooling','e-motor cooling'),('electric_motor_torque_max','torque do motor elétrico'),
 ('electric_motor_torque_max','motor elétrico torque'),('electric_motor_torque_max','electric motor torque'),('electric_range_constant_speed','autonomia a 40 km/h'),
 ('electric_range_constant_speed','autonomia em velocidade constante'),('electric_range_constant_speed','constant-speed range'),('electric_pto_power','e-PTO'),
 ('electric_pto_power','ePTO'),('electric_pto_power','tomada de força elétrica'),('electric_pto_power','electric power take-off'),
 ('exhaust_system','sistema de escapamento'),('exhaust_system','exhaust system'),('exhaust_system','escapamento duplo'),
 ('exhaust_system','dual exhaust'),('exhaust_system','ponteiras de escapamento'),('exhaust_system','exhaust tips'),
 ('four_wheel_drive_shift_max_speed','engate 4x4 em movimento'),('four_wheel_drive_shift_max_speed','shift on the fly'),('four_wheel_drive_shift_max_speed','velocidade de engate da tração'),
 ('four_wheel_drive_shift_max_speed','4x4 shift speed'),('frame_material','aço do chassi'),('frame_material','frame material'),
 ('frame_rail_section_dimensions','dimensões do perfil'),('frame_rail_section_dimensions','dimensões da longarina'),('frame_rail_section_dimensions','seção da longarina'),
 ('frame_rail_section_dimensions','frame rail section dimensions'),('front_axle_to_cab_back','eixo dianteiro até a parede da cabine'),('front_axle_to_cab_back','axle to back of cab'),
 ('gear_selector','seletor de marchas'),('gear_selector','seletor de câmbio'),('gear_selector','seletor rotativo'),
 ('gear_selector','gear selector'),('heated_steering_wheel','volante com aquecimento'),('heated_steering_wheel','volante aquecido'),
 ('heated_steering_wheel','heated steering wheel'),('hill_descent_control','HDC'),('hill_descent_control','DAC'),
 ('hill_descent_control','assistente de descida'),('hill_descent_control','controle de descida em rampa'),('hill_descent_control','controle de descida em declive'),
 ('hill_descent_control','hill descent control'),('hip_room_front','espaço para a cintura à frente'),('hip_room_front','espaço para quadril dianteiro'),
 ('hip_room_front','espaço para os quadris à frente'),('hip_room_front','hip room front'),('hip_room_front','front hip room'),
 ('hip_room_rear','espaço para a cintura atrás'),('hip_room_rear','espaço para a cintura traseiro'),('hip_room_rear','espaço para quadril traseiro'),
 ('hip_room_rear','espaço para os quadris atrás'),('hip_room_rear','hip room rear'),('hip_room_rear','rear hip room'),
 ('hybrid_energy_modes','modos híbridos'),('hybrid_energy_modes','modos de operação híbrida'),('hybrid_energy_modes','modos de operação do sistema híbrido'),
 ('hybrid_energy_modes','hybrid modes'),('hybrid_energy_modes','hybrid energy modes'),('hybrid_energy_modes','hybrid operating modes'),
 ('implement_length_max','comprimento máximo do implemento'),('implement_length_max','comprimento total do implemento (máx.)'),('implement_length_max','maximum implement length'),
 ('implement_length_max','maximum upfit body length'),('lane_departure_alert','alerta de mudança de faixa'),('lane_departure_alert','alerta de saída de faixa'),
 ('lane_departure_alert','sistema de alerta de mudança de faixa'),('lane_departure_alert','lane departure warning'),('lane_departure_alert','lane departure alert'),
 ('lane_departure_alert','LDW'),('lane_departure_alert','LDA'),('lane_keeping_assist','assistente de permanência em faixa'),
 ('lane_keeping_assist','assistência de permanência em faixa'),('lane_keeping_assist','lane keeping assist'),('lane_keeping_assist','lane keeping aid'),
 ('lane_keeping_assist','LKA'),('legroom_front','espaço para as pernas à frente'),('legroom_front','espaço para as pernas dianteiro'),
 ('legroom_front','legroom front'),('legroom_front','front legroom'),('legroom_rear','espaço para as pernas atrás'),
 ('legroom_rear','espaço para as pernas traseiro'),('legroom_rear','espaço para as pernas na segunda fileira'),('legroom_rear','rear legroom'),
 ('legroom_rear','legroom rear'),('length_with_tow_hitch','comprimento com engate'),('length_with_tow_hitch','comprimento com dispositivo de reboque'),
 ('length_with_tow_hitch','length with tow hitch'),('low_voltage_battery_warranty','garantia da bateria 12v'),('low_voltage_battery_warranty','garantia da bateria de partida'),
 ('low_voltage_battery_warranty','12V battery warranty'),('manufacturing_country','fabricado em'),('manufacturing_country','fabricado na'),
 ('manufacturing_country','fabricado no'),('manufacturing_country','modelo fabricado na'),('manufacturing_country','produzido em'),
 ('manufacturing_country','país de fabricação'),('manufacturing_country','país de origem'),('manufacturing_country','made in'),
 ('max_side_slope_angle','ângulo de inclinação lateral'),('max_side_slope_angle','inclinação lateral máxima'),('max_side_slope_angle','inclinação lateral'),
 ('max_side_slope_angle','side slope angle'),('max_side_slope_angle','side tilt angle'),('max_side_slope_angle','lateral slope'),
 ('max_side_slope_angle','max side slope'),('off_road_cruise_control','piloto automático off-road'),('off_road_cruise_control','controle de velocidade off-road'),
 ('off_road_cruise_control','off-road cruise control'),('off_road_cruise_control','trail control'),('off_road_cruise_control','crawl control'),
 ('acceleration_40_80','retomada 40-80'),('acceleration_40_80','retomada de velocidade 40-80 km/h'),('pbev_category_class','classificação na categoria'),
 ('pbev_category_class','classificação PBEV na categoria'),('pbev_category_class','classificação Inmetro na categoria'),('pbev_category_class','PBEV category class'),
 ('power_tailgate','tampa traseira elétrica'),('power_tailgate','tampa do porta-malas elétrica'),('power_tailgate','abertura elétrica do porta-malas'),
 ('power_tailgate','abertura e fechamento elétrico da tampa do porta-malas'),('power_tailgate','porta-malas elétrico'),('power_tailgate','power tailgate'),
 ('power_tailgate','power liftgate'),('rear_axle_steering','direção do eixo traseiro'),('rear_axle_steering','eixo traseiro direcional'),
 ('rear_axle_steering','direção nas rodas traseiras'),('rear_axle_steering','esterçamento das rodas traseiras'),('rear_axle_steering','rear axle steering'),
 ('rear_axle_steering','rear-wheel steering'),('rear_axle_steering','four-wheel steering'),('rear_axle_steering','4WS'),
 ('rear_cross_traffic_alert','alerta de tráfego traseiro'),('rear_cross_traffic_alert','alerta de tráfego cruzado traseiro'),('rear_cross_traffic_alert','alerta de tráfego cruzado na traseira'),
 ('rear_cross_traffic_alert','RCTA'),('rear_cross_traffic_alert','rear cross traffic alert'),('rear_cross_traffic_alert','rear cross-traffic alert'),
 ('rear_door_opening_angle','abertura das portas traseiras'),('rear_door_opening_angle','rear door opening angle'),('rear_parking_sensor_count','quantidade de sensores de estacionamento traseiros'),
 ('rear_parking_sensor_count','sensores de estacionamento traseiro (quantidade)'),('rear_parking_sensor_count','rear parking sensor count'),('rear_underseat_storage_volume','compartimento sob o banco traseiro'),
 ('rear_underseat_storage_volume','underseat storage'),('suggested_retail_price','preço sugerido'),('suggested_retail_price','preço público sugerido ao consumidor'),
 ('suggested_retail_price','MSRP'),('tailgate_load_limit','limite de carga na tampa do compartimento de carga'),('tailgate_load_limit','limite de carga da tampa'),
 ('tailgate_load_limit','tailgate load'),('tire_pressure','calibragem dos pneus'),('tire_pressure','pressão de calibragem'),
 ('tire_pressure','pressão dos pneus'),('tire_pressure','tyre pressure'),('torque_vectoring','torque vectoring'),
 ('torque_vectoring','vetorização de torque'),('turning_radius_curb_to_curb','raio de giro entre pneus'),('turning_radius_curb_to_curb','raio de giro entre guias'),
 ('turning_radius_curb_to_curb','curb to curb turning radius'),('turning_radius_wall_to_wall','raio de giro entre paredes'),('turning_radius_wall_to_wall','wall to wall turning radius'),
 ('v2l_power','potência V2L'),('v2l_power','potência de compartilhamento de energia'),('v2l_power','V2L power'),
 ('v2l_power','vehicle to load power'),('gross_vehicle_weight','peso bruto total legal'),('gross_vehicle_weight','PBT legal'),
 ('gross_vehicle_weight','PBT homologado')
) AS terms(code,term) ON a.code=terms.code
ON CONFLICT DO NOTHING;
